dsharlet/slinky

builder/copy_test.cc, builder/infer_bounds.cc, builder/optimizations.cc, builder/optimizations.h, builder/substitute.cc
- Add a test that does a reshape
- Supporting this required tweaking the copy optimization logic. In a way, it's a simplification (don't need to track `dst_d`, which was a very confusing bit of logic to get right), but it still seems like there might be a better way to do all this.
- Actually rewriting reshape copies to be efficient is a TODO. I think the matching isn't actually that hard/brittle (there's only one way to write a reshape that can optimize I think?), but it does require the simplifier to understand constraints more than it does now.
=> Add reshape test

builder/simplify.cc
It's easy to miss folded dimensions in the IR when they are rewritten from fold factor 1 to stride 0. This PR still rewrites the stride to 0, but doesn't rewrite the fold factor.
=> Don't delete fold factor when rewriting stride to 0

runtime/evaluate.cc
This prevents out-of-bound access if in the pipeline_test::parallel_stencil we change the split factor from 2 to 3.
Tested that nothing is broken with this change by running:
```
bazel test //...
```
=> Account for the min of the buffer when we assert if the buffer is folding over

apps/performance.cc, builder/checks_test.cc, builder/elementwise_test.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc
Replace the existing func::make() calls with a variadic one, with a somewhat thinner and more generic wrapper. As a bonus, the template arguments need not be specified if the callsite is a "real" function... but if it's a std::function or lambda, they still do (I haven't figured out if I can get the argument type inference working for these cases). Not sure if this is a finished product yet but PTAL.
=> Partial fix for #8

README.md, apps/performance.cc
This changes the performance app to do two copies via an intermediate buffer. This works around #22, and also produces data that is a bit more interesting (but also a bit more complicated).
Reproducing this data requires disabling the `alias_buffers` optimization, which causes the intermediate buffer to be aliased to the output, and in turn causes memcpy to behave strangely.
The test when using `memmove` and with `alias_buffers` is also interesting, but the story gets a lot more complicated still. Basically, we have the cost of two dispatches to do one operation (the other memmove is a no-op).
=> Update performance app to do 2 copies to work around #22

apps/performance.cc, runtime/buffer.h
This mostly already worked, but in order to cast to void, asserts needed to be relaxed. I realized that these asserts aren't really needed (unlike either https://github.com/dsharlet/array or Halide), because our strides are in bytes and not elements, so casts still point at the right elements.
=> Enable and test `buffer<void>` more

runtime/expr.h, runtime/print.cc
This makes the syntax a bit more consistent with other printed nodes, and makes single valued lets less verbose in the printed IR.
=> Minor tweaks to printing of lets

builder/elementwise_test.cc, builder/node_mutator.cc, builder/node_mutator.h, builder/simplify.cc, builder/simplify_test.cc, builder/substitute.cc, runtime/evaluate.cc, runtime/expr.cc, runtime/expr.h, runtime/print.cc, runtime/visualize.cc
Now that we allow crops to produce empty buffers, and expect callbacks to handle that, we have no use for if_then_else nodes.
We'll probably bring this back at some point, but we should remove it until then.
=> Remove if_then_else node

.bazelrc, builder/infer_bounds.cc, builder/optimizations.cc, builder/simplify.cc, builder/simplify_exprs.cc, runtime/expr.cc, runtime/expr.h
Minor syntax tweak to add missing overrides and enable the warning about it being missing.
=> Add missing overrides

builder/optimizations.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc, runtime/evaluate.cc, runtime/expr.cc, runtime/expr.h, runtime/print.cc
This is a step towards cleaning up bounds inference for copies, which is currently broken (#21).
=> Add "no padding" as an option for copies

builder/node_mutator.h, runtime/buffer.h, runtime/expr.h
Nit suggested by clang-tidy: when using 'override' don't also use 'virtual'
=> Don't use 'virtual' and 'override' on the same func

builder/pipeline.cc, builder/pipeline.h, runtime/expr.h, runtime/util.h
=> move ctor/op= should be marked `noexcept`

builder/copy_test.cc, builder/elementwise_test.cc, runtime/buffer.h, runtime/buffer_test.cc
These helpers make it easier to implement callbacks with other libraries that do not have arbitrary rank/stride APIs.
=> Add `for_each_contiguous_slice`, `for_each_slice`, and `for_each_tile`

runtime/expr.cc
It's a no-op and makes an unnecessary copy.
=> Don't try to move out of a const container

builder/pipeline.h, runtime/expr.h, runtime/util.h
Yet another nit found by clang-tidy. YMMV.
=> Prefer `=default` to `{]` for empty ctor/dtor bodies

MODULE.bazel, runtime/BUILD, runtime/buffer.cc, runtime/buffer.h, runtime/buffer_benchmark.cc, runtime/buffer_test.cc
This was probably a premature optimization. This PR also adds a benchmark of `for_each_contiguous_slice`
=> Tiles are span<> instead of tuple<>

runtime/BUILD, runtime/evaluate_benchmark.cc, runtime/thread_pool.cc
I realized we could pretty easily have some benchmarks of evaluating various types of nodes. These benchmarks aren't very useful in getting an absolute sense of performance, but if one were to attempt to optimize `evaluate`, the impact would hopefully be visible in these benchmarks.
The current output looks like this:
```
------------------------------------------------------------------------------
Benchmark                    Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------
BM_call                 305734 ns       305730 ns         2281 items_per_second=327.086M/s
BM_let/1                997022 ns       986753 ns          718 items_per_second=101.343M/s
BM_let/2               1257601 ns      1257603 ns …
```
=> Add benchmarks of evaluation of various stmt types

runtime/buffer_benchmark.cc
Unfortunately my CPU is affected by this hardware bug: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/2030515
Which means I can't really tell if these benchmarks are tuned quite right to be useful, but I think they should be.
=> Add benchmarks of copy/fill/pad

builder/copy_test.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc
This PR makes it so copies that are padded always have a crop that applies to the output, which defines where the padding will be applied, and more importantly, limits the bounds required of the source buffer we are (potentially) adding padding to.
This exposed some bugs in the design of the existing API, the trivial copy tests become less interesting with this change. What these two tests did (translate by an input parameter, and rely on `copy` to pad as needed) relies on the fact that the inputs to the copy were inputs to the pipeline, and the API that supported that is hard to use if the copy inputs *aren't* pipeline inputs. So, this PR removes that API entirely.
=> Padded copies must always have crops (fixes #21)

.github/workflows/ci.yml, apps/BUILD, apps/benchmark.h, builder/simplify_test.cc
- Don't actually benchmark the performance apps when testing
- Don't fuzz test as many expressions. I can't remember the last time this failed
This should save a few minutes for the github CI tests.
=> Speed up tests

.bazelrc, builder/BUILD, builder/elementwise_test.cc, builder/node_mutator.h, builder/rewrite.h, builder/simplify.cc, builder/simplify.h, builder/simplify_bounds.cc, builder/simplify_exprs.cc, builder/simplify_test.cc, builder/substitute.cc, builder/substitute.h, builder/substitute_test.cc, runtime/depends_on.cc, runtime/evaluate.cc, runtime/expr.cc, runtime/expr.h, runtime/print.cc, runtime/util.h, runtime/visualize.cc
- Speeds up `simplify` by ~5x
- Speeds up compile time of `simplify_exprs.cc` by ~2x (80s -> 40s with --config=asan in GitHub Actions)
- The mechanism for predicates is much better than the old `std::function` hack, this allowed enabling a rule that had a TODO before.
This enabled quite a bit of cleanup too, in particular we don't need the `wildcard` node any more, which always felt like a hack.
=> Implement simplifier rules with compile time pattern matching

builder/elementwise_test.cc, builder/pipeline_test.cc, builder/simplify_test.cc, runtime/buffer.cc, runtime/buffer.h, runtime/buffer_test.cc, runtime/evaluate.cc, runtime/evaluate.h
I realized that we could avoid tricky lifetime issues for `raw_buffer::make` helpers by allocating the buffer and data all in one `malloc`ed buffer. Now the result can simply be freed to clean up.
This PR also changes `raw_buffer::allocate` to return a pointer to be freed manually, instead of storing it in the class. `buffer<T, N>` now keeps a pointer to be freed, and automatically manages lifetime.
=> Clean up buffer types (fixes #81)

builder/copy_test.cc, builder/node_mutator.h, builder/optimizations.cc, builder/optimizations.h, builder/pipeline.cc, runtime/evaluate.cc, runtime/evaluate.h
There's an issue I've been thinking about for a while: if we wanted to use slinky to drive GPU dispatches instead of CPU work, that could "just work" by doing GPU dispatches in callbacks... except for copy/pad, which call `copy` and `pad`, which assume the buffer is on the CPU.
This PR maybe addresses that by making `copy` and `pad` callbacks in `eval_context` that can be customized.
This also makes it so we can test copy optimization is working as intended (much like the allocation callbacks enable testing of storage folding).
=> Make copy and pad calls customizable via evaluate callbacks

builder/pipeline_test.cc
This test is similar to the ``` parallel_stencils``` test, but there is only one input buffer which is used by both branches.
=> Adds a new test with diamond-like pipeline

runtime/BUILD, runtime/buffer.cc, runtime/buffer.h, runtime/buffer_benchmark.cc, runtime/buffer_test.cc
~~I added this as a separate API because during dev work I didn't want to involve conflicts, but~~ the API is backwards-compatible and the performance is basically identical when you pass just a single buffer (according to the benchmarks I added).
I think that the fusing and folding handling is basically correct; there might be additional opportunities for optimization (especially for folding) but I think this is ready for review.
=> Make for_each_contiguous_slice() a variadic function.

builder/copy_test.cc, builder/elementwise_test.cc, runtime/buffer.cc, runtime/buffer.h, runtime/buffer_benchmark.cc, runtime/buffer_test.cc
- Split `for_each_contiguous_slice_dim` structure into two structures to save a little stack space and simplify the code
- Let the compiler do the copy of `bases` instead of copying it from a reference (big speedup here)
- Using `size_t` as the template parameter lets the compiler infer successfully
- Use `std::apply` instead of custom wrapper (using `std::tuple_cat`)
- Reordered the arguments to the callback to have the slice extent first.
- Move `make_for_each_contiguous_slice_dims` to cc file, with special cases.
=> `for_each_contiguous_slice` tweaks and optimization

builder/pipeline.cc, builder/rewrite.h, builder/simplify.cc, builder/simplify_exprs.cc, builder/simplify_test.cc, builder/substitute.cc, builder/substitute_test.cc, runtime/depends_on.cc, runtime/evaluate.cc, runtime/evaluate_benchmark.cc, runtime/expr.cc, runtime/expr.h, runtime/print.cc, runtime/visualize.cc
- `matcher` visitor is cleaner and faster
- Some rules are easier expressed as hardcoded logic
- `==` and `!=` had some rewrites that weren't fully simplified
- `<` and `<=` had a messy set of rules
- Minor cleanups
=> Clean up simplifier

runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.cc, runtime/util.h
This seems to help ~5% fairly consistently. It's marginal, but as long as we are doing it as of #109, we might as well do it everywhere it makes sense.
=> Use SLINKY_NO_STACK_PROTECTOR in more places it makes sense

builder/copy_test.cc, builder/infer_bounds.cc, builder/pipeline.cc
I noticed the checks in infer_bounds.cc were still disabled, they should have been re-enabled in #85. That inspired me to clean up all the stale TODOs.
=> Clean up TODOs

runtime/buffer.cc, runtime/buffer.h, runtime/buffer_benchmark.cc
- A few small tweaks to `make_for_each_contiguous_slice_dims` that might be optimizations and simplify a little.
- Benchmarks are more easily compared to a speed of light for 2 buffers case.
- The 3 buffer case is not useful, it's dominated by the slow callback.
=> `for_each_contiguous_slice` minor improvements

runtime/BUILD, runtime/buffer_benchmark.cc
- Stop compilers from stripping `memset`/`memcpy` baselines
- Make the benchmark a test to get test coverage
- Fix copy_padded to actually pad
=> Benchmark cleanups

builder/infer_bounds.cc, builder/pipeline.cc, builder/pipeline_test.cc
This fixes #104, by adjusting `add_input_crops` to take the union of any existing crops rather than simply adding a crop, which effectively takes the intersection.
=> Fix bounds inference for multiple consumers of the same buffer

runtime/buffer.cc, runtime/buffer.h
Also rename the helper function to make the assert hopefully a bit more useful if it fails.
=> Move `for_each_contiguous_slice` asserts to cc file

builder/infer_bounds.cc, builder/pipeline_test.cc, builder/simplify.cc, builder/simplify_exprs.cc, builder/simplify_test.cc, builder/substitute.cc, builder/substitute_test.cc, runtime/depends_on.cc, runtime/depends_on.h, runtime/util.h
It turns out that we had a lot of bugs that were essentially accidentally working around other bugs. Untangling that mess is this PR.
- Don't try to fold storage in two overlapped dimensions at once.
- Fix a few missed/bad simplifications related to crops and loops.
- Only substitute the body of lets once instead of N times, once for each let value.
- Remove a crop added in `infer_bounds` after working through a loop (maybe related to #102)
- Reduced (but not eliminated) the hacky input crop removal.
- Substitution of shadowed expressions is more correct now.
- We can substitute buffer bounds expressions across crops and slices correctly, now it should always be "safe" to substitute buffer bounds (related to #20 and #55)
- Fix loops that use both sliding window warmup strategies (with a …
=> Fix a bunch of bugs related to pipeline construction

builder/elementwise_test.cc, builder/optimizations.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc, runtime/evaluate_benchmark.cc, runtime/evaluate_test.cc, runtime/expr.cc, runtime/expr.h
Basically this is #11. I'm not that happy with how this appears in the `func` API, I wish the attributes were attached to the callbacks themselves, so the callable would only need to be annotated with its attributes once, instead of N times at each use.
But, this is mostly a step in that direction, and it allows cleaning up the alias_buffers optimization quite a bit.
=> Add `callable_attrs::allow_in_place` and use that for aliasing

runtime/buffer.cc, runtime/buffer_test.cc
This isn't what I imagined for #122, but it at least works correctly with this PR.
=> Fix bugs when using `for_each_contiguous_slice` on broadcasted buffers

runtime/buffer.cc, runtime/buffer.h, runtime/buffer_test.cc
Found with fuzz tests that replace most of the existing hardcoded tests. It's too hard to find all the edge cases manually.
Also did this for `copy`.
=> Fix `for_each_contiguous_slice` bugs

runtime/arithmetic_test.cc, runtime/util.h
This isn't actually used currently. I had thought I was going to want to use this for evaluating expressions, but I've since abandoned that. As long as this code exists though, we should have tests for it.
=> Add tests of saturating arithmetic

runtime/buffer_test.cc
std::random_shuffle was deprecated in c++14 and removed in c++17, so this spews compiler warnings for me.
=> Replace calls to rand with a proper rng

builder/simplify.cc, builder/simplify_test.cc, builder/substitute.cc, builder/substitute.h, runtime/depends_on.cc, runtime/depends_on.h
I realized that the way the simplifier handles symbol references isn't safe, because we see symbol references from nodes that later get simplified or removed entirely. Fixing this uncovered more bugs. Fixes in this PR:
- Use `depends_on` instead of trying to avoid recursive visitors in simplify. This has bad algorithmic complexity, but it's correct. We can fix the algorithmic complexity later if/when it's a problem.
- Slices need to update *all* references to the buffer metadata, not just the bounds of the buffer itself.
- Lets need to be simplified in reverse order to get interdependent lets correct.
- `depends_on` didn't handle shadowing correctly.
=> Fix more bugs

builder/simplify.cc, builder/simplify_exprs.cc, builder/simplify_test.cc
This PR also handles `a <= b` by rewriting it to `!(b < a)` to avoid duplicating a lot of very similar rules (like Halide does).
This PR also includes some other simplifier fixes:
- We didn't substitute into the inner let values where the the let variable could have been used.
- Use a helper function to handle the right scope for setting bounds in recursive simplification.
- Fix some bugs in rewrite rules for <
- Fix unused slices being dropped entirely
=> Take < rules from Halide

runtime/buffer_test.cc
The way we seeded the RNG warned about narrowing.
=> Avoid 'narrowing' warning/error on macOS

builder/elementwise_test.cc, builder/pipeline.cc, builder/pipeline_test.cc, runtime/pipeline.cc, runtime/pipeline.h
This is something that I delayed doing for a while because it feels like a lot of boilerplate for what it is. But, I think we should have this capability, manually needing to set constants explicitly is a real pain in real use cases.
=> Support constants directly in pipeline object

builder/pipeline.cc
Running tests is extremely verbose by default. This proposes to gate the verbosity by the SLINKY_VERBOSE env var.
=> Make the verbose output in build_pipeline gated by an env var

builder/elementwise_test.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc, runtime/buffer.cc, runtime/buffer.h, runtime/pipeline.cc, runtime/pipeline.h
- The buffer_expr::make() methods that created constant buffers now take a `raw_buffer_ptr` instead of `raw_buffer*`, this allows them to take ownership of the raw buffers. Also renamed them to `make_constant()` to make the nature of the call more obvious at the call site.
- Added raw_buffer::make_allocated_external() to support the case of an all-in-one raw buffer but with element storage from elsewhere (eg memory mapped file)
- Updated tests
=> Revise constant-buffer handling

builder/elementwise_test.cc, builder/pipeline.cc, runtime/pipeline.cc, runtime/pipeline.h, runtime/visualize.cc
I have some cases where I'd like to modify the generated pipeline in some simple ways, e.g. adding extra checks. This is doable by making a new pipeline with edits (if we expose `constants` which is currently inaccessible), but I'm not sure the immutable style really makes sense for this.
=> Make `pipeline` "editable" by clients

runtime/buffer.cc, runtime/buffer.h, runtime/buffer_test.cc
Conceptually, this isn't very clean, but when you look strictly at the address arithmetic, it makes sense.
=> Relax asserts to enable broadcasting

runtime/buffer.cc, runtime/buffer.h, runtime/buffer_test.cc, runtime/util.h
I'd rather implement this by callers explicitly adding stride 0 dimensions, but doing that as needed could be relatively expensive/inconvenient. Related to #122.
=> Let `for_each_contiguous_slice` implicitly broadcast missing dimensions

apps/performance.cc, builder/checks_test.cc, builder/copy_test.cc, builder/elementwise_test.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc, runtime/buffer.cc, runtime/buffer.h
- Make rank, elem_size parameters always appear in that order
- Call constructor of `dim` in `raw_buffer::make`
The first point is a very unpleasant change, but we need to do it, and now is better than later.
=> Buffer cleanups

.bazelrc
This speeds up builds a lot, and seems like it should be independent options anyways. Tests are slower, but not slower enough to outweigh the absurdly slow builds.
=> Don't override -c dbg/-c opt with --config=asan

.github/workflows/ci.yml, builder/simplify.cc, runtime/depends_on.cc, runtime/depends_on.h, runtime/evaluate.cc
`clone_buffer` ops that don't mutate the cloned buffer metadata in the body can be substituted and removed.
=> Simplify unnecessary `clone_buffer`s

builder/copy_test.cc, builder/infer_bounds.cc, builder/pipeline.cc, builder/rewrite.h, builder/simplify_exprs.cc
- We didn't respect the old bounds when cropping in infer_bounds (missing the clamp/intersection that crop performs)
- We didn't take the union of bounds required for copies like we did for calls, or substitute the uncropped buffer like we did for calls (this broke the split test added in this PR).
- Reorder the checks so checks that the buffer exists and the rank is OK come before the extra checks added by infer_bounds.
- Add some min/max simplify rules useful for crop intersections.
- Fix a bug with the commutative variants logic, which would miss some variants if the pattern matching failed early.
=> Fix a few bugs in infer_bounds and simplify

builder/rewrite.h, builder/simplify_exprs.cc
After realizing we don't need to attempt to enumerate all the variants regardless of match state (which didn't work anyways, fixed in #178), this could be simplified further, and it's also a pretty big optimization (10%+ speedup of simplify fuzz test)
=> Simplify commute_bit logic

builder/BUILD, builder/copy_test.cc, builder/pipeline_test.cc, builder/test_util.h
The syntax for parameterized tests is IMO a little annoying, but so is having to dig through test outputs to figure out failing cases.
Fixes #25
=> Use parameterized tests for pipeline_test and copy_test

builder/replica_pipeline.cc, builder/replica_pipeline_test.cc
I have run into two things recently trying to make unrelated changes:
- Trying to make `elem_size` an expr instead of a constant ran into issues with this sizeof(T) thing
- Adding a new `intrinsic` type led me to the to_string switch that we already have.
=> Minor replica pipeline cleanups

builder/bazel_util.h
This makes it possible to run the tests in gdb without failing on the replica golden check
=> Just use the repo path when running outside bazel

runtime/BUILD, runtime/depends_on.cc, runtime/depends_on_test.cc
This enables simplification of a lot of the new `make_buffer` ops from #184 (at least while we're still substituting those bounds).
=> We were blatantly ignoring shadowing in depends_on :(

builder/elementwise_test.cc, builder/pipeline.cc, builder/pipeline.h, builder/pipeline_test.cc, runtime/buffer.cc, runtime/buffer.h
I think overloading like this makes it easier to get it right the first time. Every time I go to use these functions, I get it wrong and the compiler informs me.
=> Make `make` functions more consistent

builder/node_mutator.cc, builder/optimizations.cc, builder/pipeline.cc, builder/pipeline.h, builder/replica_pipeline.cc, builder/simplify.cc, builder/substitute.cc, runtime/depends_on.cc, runtime/evaluate.cc, runtime/expr_stmt.cc, runtime/print.cc, runtime/stmt.h, runtime/visualize.cc
The thing that motivated this is now abandoned, but I think this is a good change anyways. It should not affect performance significantly, it is more flexible this way, and it eliminates a use of size_t in the API. `make_buffer` already necessarily uses `expr elem_size` too, so this makes things more consistent.
=> Change `elem_size` from `size_t` to `expr`

builder/copy_test.cc, builder/pipeline.cc, builder/visualize/concatenate_0.html, builder/visualize/concatenate_1.html, builder/visualize/padded_stencil_0.html, builder/visualize/padded_stencil_1.html, builder/visualize/padded_stencil_2.html
All tests pass with bazel test //... --cache_test_results=no.
I think there might be a similar opportunity in slide_and_fold_storage, will look into it next.
Based on @dsharlet  branch and lot of  help from him.
=> Use bounds_of instead of substitutions

builder/optimizations.cc, builder/pipeline.cc, builder/rewrite.h, builder/simplify.cc, builder/simplify_exprs.cc, builder/simplify_test.cc, builder/substitute.cc, builder/visualize/concatenate_0.html, builder/visualize/concatenate_1.html, builder/visualize/padded_stencil_0.html, builder/visualize/padded_stencil_1.html, builder/visualize/padded_stencil_2.html, builder/visualize/parallel_stencils_0.html, builder/visualize/parallel_stencils_1.html, builder/visualize/parallel_stencils_2.html, builder/visualize/stencil_chain_split_0.html, builder/visualize/stencil_chain_split_1.html, builder/visualize/stencil_chain_split_2.html, builder/visualize/stencil_split_0.html, builder/visualize/stencil_split_1.html, builder/visualize/stencil_split_2.html, builder/visualize/stencil_split_3.html, runtime/evaluate.cc, runtime/expr.h, runtime/expr_stmt.cc, runtime/print.cc
`buffer_extent` is too much of a headache to deal with properly. For example, when substituting `buffer_min(x, y)` to be something else, `buffer_extent(x, y)` should change...somehow too, and vice versa for `buffer_extent` affecting `buffer_max`. Rather than deal with that problem, we can just get rid of it.
=> Remove `buffer_extent`

runtime/buffer.cc, runtime/buffer.h
- Don't consider `dim_sets` when it isn't present in `fuse_contiguous_dims`
- Store "plan" information in one buffer instead of two for `for_each_slice`.
This reduces `for_each_slice` overhead by 10-20%
=> Speedup and cleanup of `for_each_slice` and `fuse_contiguous_slice`

builder/pipeline.cc, builder/simplify.cc, builder/simplify.h
Tested with bazel test //... --cache_test_results=no
=> Another instance to use bounds_of

builder/slide_and_fold_storage.cc, builder/test/pipeline.cc
In the end allocation bounds were ending up depending on the loop variable.
=> Fix pyramid with async test

builder/simplify.cc, builder/simplify_bounds.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, runtime/expr.h
This PR was a bit of a rabbit hole:
- Discovered that simplify can be *much* faster if we avoid generating unnecessary intervals when we already have points.
- This tightened bounds of mod (and probably other things too), which made pyramid storage folding fail.
- The fix is to track bounds of exprs and use them in storage folding. This made some interesting changes (tightening the bounds of parallel_stencils storage folding). They look like a regression, but they're tighter expressions (probably pointlessly so in this case).
@vksnk *might* be relevant for #225 storage folding issues.
=> Speed up simplify a lot by avoiding generating bounds of points

builder/simplify_exprs.cc
This enables the monotonic check to work for all buffers in the 4x pyramid test
=> Add more rules that help with sliding window on pyramids

runtime/buffer.h, runtime/evaluate.cc
- Add slice/crop helpers for buffers, and use them in `evaluate`
- Expose part of the can_fuse and fuse helpers
=> Add more buffer helpers

.bazelrc, builder/optimizations.cc, builder/test/pipeline.cc
Before this PR, we can avoid copies by aliasing buffers, but only if the dimensions are not permuted.
This PR enables this same optimization for permuted dimensions as well.
=> Alias transposed buffers

builder/optimizations.cc, builder/pipeline.cc, builder/pipeline.h, builder/slide_and_fold_storage.cc, builder/test/elementwise.cc, builder/test/pipeline.cc, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, runtime/expr_stmt.cc, runtime/print.cc, runtime/stmt.h
This is helpful for making printed out slinky code easier to read.
=> Add `name` to call attributes

builder/pipeline.h, builder/replica_pipeline.cc, builder/test/pipeline.cc, builder/test/replica_pipeline.cc
=> Replica PIpelines should preserve `call_stmt::attributes` (#246)

builder/test/copy.cc, builder/test/elementwise.cc, runtime/buffer.h, runtime/test/buffer.cc
- `for_each_contiguous_slice` is now type safe (fixes #133)
- Adds `for_each_element`
I think that we should consider removing `for_each_slice` entirely. It's very hard to make it type safe. Existing uses of it can use `for_each_element`, and just explicitly slice the leading dimensions as desired first. The implicit slicing of buffers in `for_each_slice` can be confusing, because there is some accommodation for missing dimensions at both ends of the dimension list. `for_each_element` eliminates the leading dimensions from consideration, and requires the user to explicitly slice those as they see fit.
The downside is that the callback only gets a pointer and not a buffer, so if a buffer object is required, the user needs to construct one inside the callback.
=> Buffer helper improvements

runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.cc, runtime/test/buffer.cc
This replaces the implementation of copy/fill/pad with `for_each_element`. This fixes a bunch of issues:
- copy/fill/pad's implementation was highly redundant with `for_each_element`
- copy/fill/pad didn't support folded buffers (#41)
- `for_each_element` didn't support padding
=> Implement `copy`/`pad`/`fill` using `for_each_element`

runtime/buffer.cc, runtime/buffer.h
`memset` should be faster than `fill_n` when the type is more than one byte, and also should make debug/unoptimized builds a lot faster.
=> Optimize multi-byte fills to use memset when possible

runtime/buffer.cc, runtime/test/buffer.cc, runtime/test/buffer_benchmark.cc
- Recovers much of the performance lost in #261 
- Remove a few more uses of for_each_index from tests
=> Minor cleanup and optimization of buffer helpers

builder/simplify.cc, builder/test/simplify.cc, builder/test/softmax.cc, runtime/print.cc
This moves loop invariant stmts from the beginning of loops only out of the loop. This does part of what is discussed in #270. 
I decided to just add a TODO for more complicated forms of LICM, which may not really be possible to have in the first place. I can't think of a realistic way to have a loop invariant stmt consume a buffer that is produced by a loop-variant stmt. Everything I can think of would do weird things like read uninitialized memory.
=> Simplify some loop invariant code

builder/pipeline.cc, builder/test/pipeline.cc
This fixes an issue where constraints on bounds of inputs or outputs would propagate into intermediate buffers and their crops.
=> Always use symbolic bounds for output bounds

builder/pipeline.cc
This doesn't fix any actual issue I know of, but it seems right, like #278 for buffers.
=> Use symbolic bounds for loops in addition to input crops (like #278)

builder/simplify.cc, builder/test/simplify.cc, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/buffer.h, runtime/depends_on.cc, runtime/depends_on.h, runtime/test/depends_on.cc
There are cases in which substitute can fail if the value uses buffer metadata shadowed by crops/slices that are hard to detect by depends_on. Rather than try to fix this, we should just not try to substitute non-trivial lets.
=> Stop substituting lets unless they are trivial

builder/test/simplify.cc, builder/test/substitute.cc
Replace `test_simplify`, `test_substitute`, and similar helpers with uses of ASSERT_THAT and a custom matcher.
The motivation for this: I'm working on a large change to the simplifier, these tests are failing often and need a lot of debugging. It's really annoying to figure out exactly which test is failing, because the reported failure line is in `test_substitute` or similar. We can't simply use ASSERT_EQ because we overload operator== for expr in a different way. Calling `match` via an ASSERT_THAT matcher is easy and solves all these problems.
There was similar discussion on #279 but I think this use is much lighter weight.
=> Use ASSERT_THAT for simplify/substitute tests

builder/node_mutator.cc, builder/optimizations.cc, builder/pipeline.cc, builder/simplify.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/test/simplify.cc, builder/test/substitute.cc, runtime/depends_on.cc, runtime/depends_on.h, runtime/evaluate.cc, runtime/expr_stmt.cc, runtime/print.cc, runtime/stmt.h, runtime/test/depends_on.cc, runtime/test/evaluate.cc, runtime/test/evaluate_benchmark.cc, runtime/visualize.cc
I discovered yet another challenging bug to fix with shadowing in the simplifier, so I've decided to give up on supporting shadowing there.
In order to do this, we need to be able to rewrite programs to never shadow, and to do that, we need to allow buffer mutators to take an src buffer. This PR does that, but does not actually stop shadowing yet.  This PR reproduces existing behavior exactly (surprisingly), but with the extra optional parameter to buffer mutators. 
The next step will be to generate programs that do not have shadowing, and remove the ability for the simplifier to understand shadowing, which should be a big reduction in complexity and avoid probably many undiscovered bugs. We will also want to rewrite programs to shadow before evaluation, which is faster if buffer mutators …
=> Refactor buffer mutators to take an `src` buffer instead of always working in place

builder/optimizations.cc, builder/test/simplify.cc, builder/test/substitute.cc, runtime/buffer.h, runtime/evaluate.cc, runtime/evaluate.h
These commits keep floating around my WIP branches:
- Remove unused includes
- Use `dim` helper functions where appropriate
- Clean up `allocate`/`free` callback usage
- Clean up `make_buffer` usage for copies that was confusing/tricky, it basically a product of trial and error without thinking.
=> A bunch of minor fixes from other WIP branches

builder/pipeline.cc
I've been looking at this code as part of another change, peeling of some minor cleanups, mostly avoiding use of `container::size()` as a signed integer where possible
=> Minor pipeline cleanups

base/ref_count.h, builder/pipeline.cc, builder/pipeline.h, builder/replica_pipeline.cc, builder/test/BUILD, builder/test/copy.cc, builder/test/replica_pipeline.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, runtime/buffer.cc, runtime/buffer.h
Before this PR, we only cropped inputs (and confusingly called it `output_crop`), and relied on `copy` treating out of bounds values as undefined.
This doesn't work well when copying buffers with broadcasting, because nothing is out of bounds in broadcasted dimensions.
This PR fixes these problems by cropping both the input and output of copies in concatenates, and fixes a bug where we forgot to sanitize crops of buffer metadata.
=> Crop both inputs and outputs of concatenates

builder/optimizations.cc, builder/simplify.cc, builder/simplify_bounds.cc, builder/test/copy.cc, runtime/evaluate.cc, runtime/expr.h, runtime/expr_stmt.cc
This PR allows constructing copies that broadcast or copy in a dimension based on a runtime condition.
This PR also contains some minor refactoring/optimization of `evaluate` related to evaluating intervals that might be points.
=> Support optional broadcast copies

builder/optimizations.cc, builder/optimizations.h, builder/simplify.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/pipeline.cc, builder/test/util.h, runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.cc
This PR is a bunch of changes that enable optionally broadcasted copies from #294 to alias when possible:
- `slice_buffer` and `slice_dim` can now slice out of bounds, which makes the buffer base null. This makes it consistent with `for_each_element` and related helpers, which is necessary to make `copy_stmt` implementations correct when not doing any of the optimizations for copies.
- Attempt to alias copies for the case that either the `src` or `dst` is an allocation.
- Expand `is_copy`'s ability to understand these dynamic broadcast or copy copies.
- A whole lot of refactoring of aliases/copy implementation passes. I think there were a few bug fixes in here. I hope to clean this up further still, this code is too hard to understand currently. I think it can be improved a lot once I …
=> Enable optionally broadcasted copies to alias

runtime/test/buffer_benchmark.cc
This makes the calls to `memset`/`memcpy` compile-time constants (or not) where appropriate
=> Fix benchmarks to be more realistic

base/test/BUILD, base/test/bazel_util.cc, base/test/bazel_util.h, builder/test/BUILD, builder/test/pipeline.cc, builder/test/softmax.cc, builder/test/util.cc, builder/test/util.h, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/visualize.cc
- Fix visualization bug when loops variables were shadowed
- Change visualization timing to show all produces from a given call/copy at the same timestep
- Add visualization to the softmax pipeline
- Some minor cleanup of deps/headers for visualization in tests
=> Fix visualization bugs and add visualization for softmax

builder/optimizations.cc, builder/test/copy_pipeline.cc, builder/test/elementwise.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/buffer.cc, runtime/buffer.h, runtime/test/buffer.cc, runtime/visualize.cc
`alias_buffers` was the last thing I'm aware of that relied on broadcasting hacks. This PR cleans up `alias_buffers` to hopefully make it easier to understand (mainly by breaking the `copy_stmt` visitor into separate cases for aliasing the src and dst, which are different), and stops relying on the broadcasting hacks by correctly setting the bounds of dimensions that we read broadcasts from. This PR then removes the broadcasting hacks!
=> Clean up alias_buffers and remove broadcasting hacks

builder/optimizations.cc, builder/pipeline.cc, builder/test/copy_pipeline.cc, builder/test/elementwise.cc, builder/test/pipeline.cc, builder/test/replica_pipeline.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/buffer.cc, runtime/buffer.h, runtime/depends_on.cc, runtime/evaluate.cc, runtime/expr_stmt.cc, runtime/test/buffer.cc, runtime/visualize.cc
Before this PR, default strides were set during pipeline construction. This was flawed because if a user set some strides and not others, the default generated strides would be confused. This issue is now fixed.
It additionally allows quite a few improvements:
- Allows the calling program more control over strides, such as to control alignment/padding. 
- Allows us to tell when strides are fixed vs. flexible. Right now, aliased buffers will ignore the strides set by the user, potentially invalidating them and violating assumptions the callbacks have made.
- The automatically generated strides algorithm is much more robust (taken from https://github.com/dsharlet/array/blob/38f8ce332fc4e26af08325ad0654c8516a445e8c/include/array/array.h#L897-L907, but we don't need to accommodate compile …
=> Change default strides to be determined by buffers/allocation callbacks instead of pipeline construction

builder/pipeline.cc, builder/test/BUILD, builder/test/tile_area.cc
This required a small bug fix: we forgot to sanitize the loop steps (a user provided expression) of buffer metadata.
=> Add a test that splits loops to a maximum total area

builder/pipeline.cc, runtime/print.cc, runtime/print.h, runtime/test/buffer.cc
I found this quite helpful while debugging.
=> Add an option to set node_context for print globally

builder/optimizations.cc, builder/test/BUILD, builder/test/cannot_alias.cc
If the client code sets a constraint on the stride of an allocation, we should not violate that constraint with an alias with a different stride in that dimension.
This PR adds a test that verifies this, and implements the logic necessary to implement this.
=> Avoid aliasing buffers that would violate constraints

builder/simplify.cc, builder/substitute.cc, builder/test/simplify.cc, builder/test/substitute.cc
- Don't add redundant clamps in `substitute`
- Fix a few bugs due to non-shadowed crop simplification.
=> `simplify` and `substitute` fixes

builder/optimizations.cc, builder/pipeline.cc, builder/test/pipeline.cc, builder/test/visualize/padded_stencil_2.html
Leaving crops as inputs to copies was a holdover from before fixing cropped copies properly (by passing the crop bounds from externally instead of relying on the bounds of the src buffer).
Removing this crop exposed some aliasing bugs. I attached these fixes on top of another WIP aliasing branch, which did some refactoring of aliasing. It might help to look at the commits on this branch in isolation, because only the last commit https://github.com/dsharlet/slinky/commit/017b39eebc75ec9f1f739bac5f5123cf2f7a4afa does anything interesting.
=> Remove crops from copy inputs (like calls) and related aliasing fixes

builder/simplify.cc, builder/simplify.h, builder/simplify_bounds.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/test/pipeline.cc, builder/test/simplify.cc, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html
This started out by adding one little rule to canonicalize constants to the RHS of less than, and it turned out that this unlocked a bunch of improvements.
- Add rule to canonicalize constants to the RHS of <, which helps some things simplify more.
- Add rules for finding bounds of `min(x, y) - max(z, w)`. When terms from each side of the subtract are correlated, we might have a tighter bound. This appears in fold factor expressions.
- Add `constant_upper_bound` helper, useful for fold factors.
The combination of these things means slide_and_fold_storage doesn't need hacks to replace loop bounds with infinity any more.
This also fixes an issue identified by @vksnk: we currently allowed folding to happen even when there was a consumer outside the loop we fold in. We simply missed this by …
=> Improve sliding window and storage folding robustness

builder/optimizations.cc, builder/test/copy_pipeline.cc
Also some minor refactors that hopefully make it easier for me to keep it straight which buffer is which when aliasing, and a small lifetime cleanup.
=> Fix aliased copies when the src is aliased to a translated dst

runtime/buffer.cc, runtime/buffer.h, runtime/test/buffer.cc
We used to rely on this for concatenate to work, but now that that is cropped properly, we should stop doing this. It makes it easier to reason about copies for aliasing, and in general I think it's better.
=> Remove undefined padding mode for `copy`

builder/optimizations.cc, builder/pipeline.cc, builder/replica_pipeline.cc, builder/rewrite.h, builder/simplify_exprs.cc, builder/test/cannot_alias.cc, builder/test/copy_pipeline.cc, builder/test/pipeline.cc, builder/test/replica_pipeline.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html
This PR adds a check when considering a buffer for aliasing that the aliasing target is big enough.
This required a bunch of new simplifier rules to enable proving that x <= y where x, y are bounds of buffers.
Also fixes a bug where the replica pipeline generator dropped the padding of copies.
This PR adds a few new tests that aren't passing the way they should yet (the checks are commented with TODOs). It also disables the check for aliasing in padded_stencil, which either needs major simplifier upgrades to be able to prove is safe for aliasing, or needs the alias_buffers pass to grow the allocation to the union of the original and the aliases (I'm going to attempt that in my next aliasing PR).
=> Check that alias targets are big enough

builder/simplify.cc, builder/test/simplify.cc, runtime/print.cc
These simplifications were pretty buggy if the resulting operation was not a shadow of itself.
=> Fix simplifications of `make_buffer` when not self shadowing

builder/simplify_exprs.cc, builder/test/simplify.cc
- New rules for `select`
- We apparently don't need rules to simplify `buffer_min`/`buffer_max` comparisons, which is great because these rules assumed that buffers were non-empty, which is not true.
- Reorder and clean up redundant rules for `<`, `min`, `max`
- Replace buggy substitutions for `select` with rules
=> Simplify rule cleanups and new select rules

builder/simplify.cc, builder/simplify_exprs.cc, runtime/expr.h
Something like this was originally added in #321, but reverted in #333 because it wasn't correct.
This PR adds something similar back, but it should be safe. This is stronger than the rules that tried to do this, because there might be an intervening op, and I don't want to add all the permutations of rules that might be necessary for this.
=> Stronger simplification of nested selects

base/test/BUILD, base/test/bazel_util.h, base/test/seeded_test.h, builder/test/BUILD, builder/test/simplify.cc, runtime/test/BUILD, runtime/test/buffer.cc
This fixes #236, which is blocking running massive amounts of fuzz testing easily, which I plan to do soon.
Inspired by https://github.com/google/XNNPACK/blob/e6ba3d0421c99bea58d0d144561ef921648046d6/test/replicable_random_device.h#L28
=> Add gtest_seeded_rng and use it in randomized tests (fixes #236)

builder/pipeline.cc, builder/simplify_exprs.cc, builder/test/simplify.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/evaluate.cc, runtime/expr.h, runtime/expr_stmt.cc, runtime/print.cc, runtime/test/evaluate.cc
Until now we were pretty sloppy about short circuiting. We rely on short circuiting to avoid integer overflow in some checks. 
#337 made simplification of logicals a lot more aggressive, and looking at the code, I'm not sure we actually got short circuiting anyways.
This PR adds `and_then` and `or_else` intrinsics that are more explicit about wanting short circuiting.
=> Add short-circuiting `and_then` and `or_else` intrinsics

.bazelrc
Currently, our bazelrc causes a recompile when switching between `bazel run` and `bazel test`, which is a bit annoying. This is also just a nice cleanup to not duplicate all our options 3x.
=> Fix bazelrc copts being different between build, run, test

builder/slide_and_fold_storage.cc, builder/test/softmax.cc
Related to efforts about aliasing folded buffers. There are cases right now where the fold factors we come up with are wrong, but aliasing comes along later and aliases the buffer, so we don't see it.
=> Fix fold factors getting clobbered by a different loop

builder/test/simplify.cc
I think this is one of the reasons we don't hit #347 in the test.
=> Don't decrease depth twice for make_random_condition

builder/rewrite.h, builder/simplify.cc, builder/simplify_exprs.cc, builder/test/simplify.cc
- Add ability to print patterns, makes it much easier to debug simplify issues.
- Fix bad rules (fixes #354, fixes #335).
- Rework mod rules to be more explicit about changing comparison -> mod, and then simplify the mod.
- Don't require evaluated constant expressions to be canonical, and remove a hack workaround for this.
- Remove buffers from fuzz tester, they are annoying and don't add much now that we don't have rules for these.
=> Simplifier improvements

builder/simplify_rules.h, builder/test/simplify/rule_tester.h
Most of these fixes would never matter in practice, because recursive simplifications would catch them first. But I think it's better if every rule is fully correct and does not rely on other simplifications running first.
=> Strengthen rule tester and fix issues it finds

.github/workflows/ci.yml, builder/test/cannot_alias.cc, builder/test/context.h, builder/test/copy_pipeline.cc, builder/test/pipeline.cc, builder/test/pyramid.cc, builder/test/softmax.cc
Asserts of the form `ASSERT_EQ(ctx.heap.total_size, buf1_size + buf2_size + ...)` are hard to debug and maintain because it's hard to tell which buffer is wrong.
This PR changes this to use ASSERT_THAT and a matcher that lets us specify the size of each buffer we expect to find.
=> Use ASSERT_THAT container checks for allocation asserts

builder/test/copy_pipeline.cc, builder/test/pyramid.cc
=> Remove duplicate symbols in tests

builder/slide_and_fold_storage.cc, builder/test/util.cc
This addresses the issue in #363.
The issue is that loop bounds may refer to buffer_min/buffer_max of some buffer which are inferred by bounds inference and are outside of the actual buffer bounds. This is a problem because the buffer_min/buffer_max will be clamped to the actual buffer bounds during evaluation (and maybe in some other places).
=> Update loop bounds after sliding

base/chrome_trace.cc, base/chrome_trace.h, builder/BUILD, builder/optimizations.cc, builder/pipeline.cc, builder/simplify.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc
This shows that `where_true` is a big problem and why the softmax tests are so slow. It also revealed an inappropriate use of `attempt_to_prove`
=> Add tracing to `build_pipeline` and its callees

builder/slide_and_fold_storage.cc, builder/test/softmax.cc
This will also fix the correctness issues similar to #376, but also should achieve the same effect as #305.
=> Move substitute_bounds for loop bounds to be before visiting the body

builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/visualize.cc
Fixes #374; also cherry-picks the fix for nested-let-expr and saniziting `#` from #375
=> Fix visualizer output (#374)

base/span.h, builder/simplify.cc, builder/simplify_rules.h, builder/substitute.cc, builder/substitute.h, builder/test/simplify/simplify.cc, builder/test/util.h, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/depends_on.cc, runtime/depends_on.h, runtime/expr_stmt.cc, runtime/test/depends_on.cc
This PR attempts to simplify things more strongly using existing buffer information:
- Try to rewrite more `make_buffer` ops to be `crop_buffer`/`transpose`/etc. where possible.
- Simplify crop bounds more strongly. This fixes some recent regressions.
=> Improve simplification of buffer bounds

builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_0.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_0.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html, runtime/visualize.cc
For better or worse, the visualizer goldens serve as a golden test for the slinky code generation. Reading these is a bit annoying because the `min:` and `max:` struct fields are easy to confuse with `min(., .)` and `max(., .)` ops unless reading very carefully.
=> Change intervals from structures to arrays

builder/simplify.cc, builder/test/simplify/simplify.cc, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html
This attempts to simplify crops like `min(y, buffer_max(b, 0)) + 2` when the buffer being cropped has bounds `buffer_max(b, 0) + 2`, which is common in stencil pipelines.
=> Stronger simplification of crop bounds

builder/test/pipeline.cc
I removed this when working on #391 and forgot to put it back
=> Add parallel version of outer_product tests

runtime/evaluate.cc, runtime/expr.h
This is a pretty big speedup, and is a step towards eliminating stack usage in `evaluate`.
Fixes #2
```
Benchmark                             Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------------------------------------------
BM_call                            -0.4684         -0.4684        489570        260266        489571        260266
BM_let/1                           -0.0445         -0.0445       1112999       1063439       1113001       1063437
BM_let/2                           +0.0264         +0.0264       1334519       1369738       1334523       1369737
BM_let/3                           +0.0562         +0.0562       1592467       1681900       1592470       1681902 …
```
=> Replace visitor with switch statements in `evaluate`

.bazelrc, apps/performance.cc, base/arithmetic.h, base/test/BUILD, base/test/arithmetic.cc, base/test/arithmetic_benchmark.cc, runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.cc
This is a bunch of small optimizations/cleanups, and a few bigger things:
- The "for each" loops are now defined by flags (linear, folded) and (call f, don't call f).
- Instead of inlining the loops into the branch that decides which kind of loop/call to make, inline the decision into the loops.
- Add fast path for slice of one dimension.
=> Optimize and clean up buffer traversal helpers

builder/node_mutator.h, builder/pipeline.cc, builder/pipeline.h, builder/replica_pipeline.cc, builder/simplify.cc, builder/substitute.cc, builder/test/cannot_alias.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/pipeline.cc, runtime/expr.h
- Allow using intermediate buffer bounds in the pipeline, by moving the sanitized expressions to be after constructing the allocation bounds.
- Allow constructing expr from size_t, and clean up related hacks.
- Fix a simplify bug
This adds reshape tests to copy_pipeline that use the new functionality
=> Pipeline construction improvements

builder/optimizations.cc, builder/substitute.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc, runtime/depends_on.cc, runtime/stmt.h
This PR is a bit of a hack to allow aliasing reshapes implemented by a callback to memcpy. It makes `memcpy` a special callback name that we recognize in aliasing.
This is a workaround for #187, which we should still try to do, but it's quite difficult.
=> Allow aliasing "flat" copies

base/test/BUILD, base/test/thread_pool.cc, base/thread_pool.cc, base/thread_pool.h, builder/test/context.cc, runtime/BUILD, runtime/evaluate.cc, runtime/evaluate.h, runtime/test/evaluate.cc, runtime/test/evaluate_benchmark.cc
I think we need to add helpers to parallelize work within callbacks. To enable working towards that, this PR refactors the thread pool to move `parallel_for` from inside `evaluate` to be a public function of `thread_pool`.
This also cleans up a bit of an annoying wart in how customizing parallelism worked through `std::function`. This may also have had some extra overhead.
=> Refactor thread pool to make `parallel_for` more broadly available

builder/pipeline.cc, builder/test/visualize/softmax_split_0.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html
The problem was that bounds of make_buffer's were using global variables which are defined inside of the make_buffer body (incorrect because bounds were using undefined variables). Later the simplifier would substitute make_buffer bounds into lets which caused the incorrect ordering of the lets (seems like it might be also a bug in simplifier).
=> Fix sanitizer ordering issues

builder/simplify.cc, builder/test/simplify/simplify.cc
This is pretty expensive, but it is necessary to simplify some kinds of expressions. See the test for a simple example.
=> Try comparing bounds to values when simplifying `min` and `max`

builder/optimizations.cc, builder/test/elementwise.cc
This makes us able to alias in-place ops regardless of the allocation order.
It *seems* like this should require more safety checks, but I can't seem to construct a pipeline that does bad aliasing with this change.
=> Consider both inputs and outputs as alias candidates for in-place ops

builder/simplify.cc, builder/test/simplify/simplify.cc
- Due to aliasing, we sometimes end up with multiple crops of the same buffer with the same parameters. This PR adds simplifications to eliminate these redundant crops.
- Improves the buffer dim canonicalization to succeed in more cases, which lets use rewrite more `make_buffer` ops as `transpose` ops.
=> Buffer simplification improvements

base/chrome_trace.cc
It was failing to load a trace file because it didn't like the empty event in the beginning. Also, for whatever reason it didn't like the long thread ids, so had to add quotes for it to be able to handle multi-threaded traces.
This is a matter of taste, but IMO ui.perfetto.dev has a better UI compared to the built-in viewer and allows to get a lot of aggregated statistics, etc, while still handling everything locally. The great benefit though is that allows uploading and sharing traces with other people which I think is extemely convinient. Example: https://ui.perfetto.dev/#!/?s=17bcbcc16c0c8d6157bae9020e0c1d5e53a00db56841169fcdb9b885ea309e5e
=> Minor changes to support viewing traces in ui.perfetto.dev

base/chrome_trace.cc, base/test/BUILD, base/test/thread_pool_benchmark.cc, base/thread_pool.cc, base/thread_pool.h
- Add some limited spinning before falling back to condition variable. This should avoid wasting much CPU, but also helps keep threads ready between tasks. Measurably improves a real workload.
- Clean up logic to avoid running the same task recursively on one thread.
- Add benchmark (not really that useful yet...)
=> Thread pool improvements

builder/simplify.cc, builder/test/simplify/simplify.cc
This PR makes LICM stronger, by allowing it to make non-loop-invariant stmts loop invariant when it is safe to do so. It works by replacing the loop variable with `expr()` only in crop bounds, and only if those crops are not cropping a folded dimension. If there are other uses of the loop variable (e.g. in a slice), the stmt will not be made to be loop invariant.
This seems like a hack, but this kind of simplification has gotten us really far already...
=> Strengthen LICM

base/thread_pool.cc, base/thread_pool.h
This makes nested parallel loops run a bit better
=> Cancel in-flight tasks when we don't need them any more

builder/optimizations.cc, builder/simplify.cc, builder/test/copy_pipeline.cc, builder/test/pipeline.cc
This simplification assumes that the base is aligned with the min, but it's not the case for folded dims.
=> Skip simplifying buffer_at arg if the dim is folded

runtime/buffer.cc, runtime/buffer.h, runtime/test/buffer.cc
This makes it so `for_each_contiguous_slice` and `for_each_element` will still use contiguous slices or linear loops for folded dimensions if the buffer doesn't cross a folded dimension.
We could do better still if we could just use n linear/contiguous chunks between the fold boundaries, but that's much harder to do.
=> Check if we actually cross a fold, rather than just if the dim is folded

builder/test/funcs.h, runtime/buffer.h, runtime/evaluate.h
It's a minor annoyance to have to make a variable with the fill value to take the address of, this PR solves that.
=> Add typed overloads of copy/fill/pad

builder/substitute.cc, builder/substitute.h, builder/test/optimizations.cc, runtime/expr.h, runtime/expr_stmt.cc
`deshadow` was very slow due to two algorithmic complexity issues:
- The way `substitute` handled shadowing was very inefficient: tracking all shadowed variables, and checking at substitute time if a substitution should be disallowed due to shadowing. Now, we stop traversing the IR as soon as any possible substitutions become shadowed, which also avoids the expensive way we tracked shadowed variables (linear search in a vector).
- `insert_unique` used a linear search to find an unused symbol name, and a linear search to check if a symbol name was used, both are fixed.
The test added in this PR took ~3 seconds before these fixes, and now takes 150ms, where almost all the time is spent in `insert_unique`. It could be improved further, but not easily, and it's not worth doing for now.
=> Fix deshadow slowness

builder/pipeline.cc, builder/test/visualize/padded_stencil_2.html, builder/test/visualize/parallel_stencils_0.html, builder/test/visualize/parallel_stencils_1.html, builder/test/visualize/parallel_stencils_2.html, builder/test/visualize/softmax_split_1.html, builder/test/visualize/softmax_split_4.html, builder/test/visualize/stencil_chain_split_serial_split_1.html, builder/test/visualize/stencil_chain_split_serial_split_2.html, builder/test/visualize/stencil_chain_split_serial_split_3.html, builder/test/visualize/stencil_chain_split_serial_split_4.html, builder/test/visualize/stencil_split_1.html, builder/test/visualize/stencil_split_2.html, builder/test/visualize/stencil_split_3.html
One of the internal tests was producing incorrect results because of the loop variables being mixed up.
=> Assign unique loop vars during the IR construction

base/arithmetic.h, base/modulus_remainder.h, base/test/arithmetic_benchmark.cc, base/test/modulus_remainder.cc, builder/simplify.cc
The Halide version used this tricky helper function: https://github.com/halide/Halide/blob/1a7b91426b26f94eec76d4b19a9a3f04e74b7c47/src/ModulusRemainder.cpp#L13
=> Fix lost alignment info when modulus = 0

builder/optimizations.cc, builder/test/context.cc, builder/test/context.h, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/funcs.h, builder/test/util.h, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, runtime/buffer.cc, runtime/test/buffer.cc
When we tried to expand allocations to accommodate a possibly padded alias, we used the "native" coordinates for both buffers, which is incorrect if there is a translation between the aliases. This PR fixes that.
Some related notes:
- The old "replace copy with pad" logic was pretty broken, and also pointless, because pad simply called copy with an aliased buffer anyways, expecting the copy parts of the operation to be a no-op. We might want to optimize this at some point, but it's low priority for the moment.
- The asserts added in #455 were overzealous if the buffer is empty, fixed this to allow empty buffers.
=> Fix incorrect aliasing for translated copies

builder/test/funcs.h, builder/test/pipeline.cc
I guess `char` is not always signed?
=> Avoid `char` signed integer overflow

builder/optimizations.cc, builder/pipeline.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html
- We never actually applied the input_crop except in bounds inference, which didn't affect copies from inputs.
- Use the correct set of bounds when handling nested aliases, i.e. an allocation that gets combined with another allocation more than once.
- Propagate information about aliases to subsequent aliases, so aliases that alias other aliases work correctly.
=> Bug fixes for sequences of padded copies

builder/simplify.cc, builder/test/simplify/simplify.cc
If a buffer comes from outside the pipeline, we might not know about all of its dimensions in the simplifier. There were a few places where we didn't account for this, resulting in bugs.
=> Fix issues when transposing a buffer from external to the pipeline

base/thread_pool.h, builder/optimizations.cc, builder/substitute.cc
- Classes with virtual methods need virtual dtors
- Fix ambiguous size_t -> expr conversions
- Various clang-tidy fixes re: includes
=> Various minor fixes

runtime/buffer.h, runtime/expr.h
Reverts dsharlet/slinky#475 -- change was misguided and incomplete.
=> Revert "Fixes for compiling Slinky under Emscripten"

base/chrome_trace.cc, base/modulus_remainder.h, base/util.h, builder/rewrite.h, builder/simplify.cc, runtime/buffer.h, runtime/evaluate.cc, runtime/expr.h
Various fixes to improve portability to targets/compilers that we hadn't tested on (much): 
- index_t needed some love to avoid multiple issues:
- on 32-bit systems we really want it to be a 32-bit type for efficiency; there were various templated functions that assumed it was always an int64_t that needed to use an `index_t` (or `T`) as the temporary instead
- defining `index_t` as `ptrdiff_t` or `intptr_t` seems like the right thing but introduces pain on some compilers (eg Emscripten, AppleClang) where the result is a `long` type that is distinct from both `int32_t` and `int64_t`, making it painful to get the overloaded ctors for `expr` correct without an ugly mass of ifdefs. Instead, I chose to use `std::conditional` to make it explicitly `int32_t` or `int64_t` to dodge that …
=> Various portability fixes for Slinky

builder/pipeline.h
Right now, if you call make that is malformed somehow, the risk of infinite recursion is high, due to one of the overloads accepting  almost anything, and then calling itself if it can't map it to one of the other overloads.
This PR causes such cases to fail at compile time instead.
=> Reduce risk of infinite recursion when calling func::make

base/ref_count.h, base/util.h
https://clang.llvm.org/docs/AttributeReference.html#trivial-abi 
This PR adds SLINKY_TRIVIAL_ABI and annotates ref_count with it.
The binary size (measured internally) impact: libruntime.so: 321K -> 315K, libruntime.a: 413K -> 406K
=> Introduce SLINKY_TRIVIAL_ABI

.bazelrc, base/arithmetic.h, base/chrome_trace.cc, base/chrome_trace.h, base/test/BUILD, base/util.h, builder/optimizations.cc, builder/rewrite.h, builder/simplify.cc, builder/simplify_bounds.cc, builder/simplify_exprs.cc, builder/simplify_rules.h, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/substitute.h, builder/test/simplify/rule_tester.h, runtime/depends_on.cc, runtime/expr.h, runtime/expr_stmt.cc, runtime/print.cc, runtime/print.h, runtime/stmt.h, runtime/test/BUILD, runtime/visualize.cc
This PR is a bunch of minor changes that reduce code size (~30%) and speed up the simplifier for expressions (~2.5x):
- Remove templating where it is marginally useful
- Mark helper functions `static` and/or `inline` where appropriate
- Use `std::move` in more places, especially headers where possible
- Some tweaks to how the simplifier rewriter works to do more work at compile time, which can result in simpler code
=> Reduce code size and speed up simplifier

builder/rewrite.h, builder/simplify_rules.h, builder/test/simplify/rule_tester.h
This allows writing multiple rules with the same pattern more concisely, and generates smaller and faster code because we only attempt to match the expression once for multiple rules with the same pattern.
=> Add support for multiple replacement, predicate pairs in rewrite rules

builder/node_mutator.cc, builder/node_mutator.h, builder/optimizations.cc, builder/pipeline.cc, builder/rewrite.h, builder/simplify.cc, builder/simplify_bounds.cc, builder/simplify_exprs.cc, builder/substitute.cc, builder/substitute.h, builder/test/simplify/rule_tester.h, runtime/depends_on.cc, runtime/depends_on.h, runtime/expr.h, runtime/expr_stmt.cc, runtime/stmt.h
This is a messy change. The core of it is as the title says: make `expr(const base_expr_node*)` and similar for `stmt` `explicit`. This uncovered a few places where we were doing silly things, like constructing an `expr` just to call a helper function that doesn't affect the lifetime of its argument.
The rest is a wrapper to attempt to avoid requiring explicit conversions everywhere, but without the excessive reference counting due to constructing temporary `expr` objects.
This speeds up the simplifier by 5-10%, and *should* reduce code size, but I think the compiler is inlining more than before this change, so it's a wash.
=> Make `expr(const base_expr_node*)` and `stmt(const base_stmt_node*)` explicit

builder/simplify.cc
`less_equal` canonicalizes to `less`, and it's not cheap to do so.
This speeds up simplify of random expressions by ~15%
=> Use `less` instead of `less_equal` to prove things

builder/pipeline.cc, builder/test/pipeline.cc, runtime/buffer.cc
This can happen if this func output isn't used as an input by any other func in the pipeline (and isn't an output of the pipeline itself).
=> pipeline_builder needs to ensure all outputs have allocation_bounds

builder/replica_pipeline.cc, builder/test/replica_pipeline.cc
replica_pipeline.cc fails to compile because of ambiguity between `int` and `long` on Bazel + XCode; explicitly casting it to `index_t` heals it portably.
=> Fix ambiguous compilation under bazel on macOS

builder/replica_pipeline.cc, builder/rewrite.h, builder/simplify.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/test/replica_pipeline.cc, runtime/depends_on.cc, runtime/evaluate.cc, runtime/expr.h, runtime/expr_stmt.cc
They now return `std::optional<T>` instead of `const T*`. This turns out to matter in subtle cases like
```
int foo = *as_constant(simplify(thing()));
```
where the return value of `simplify` is a temporary that's discarded immediately, but that as_constant() assumes will remain valid. Using `std::optional` captures the value in a way that should be safer against this pattern, as well as more easily debuggable (since dereferencing an empty std::optional is caught by clang-tidy in many cases and is also checked for by debug builds of libc++).
=> Upgrade as_constant and as_variable

builder/simplify.cc, runtime/expr.h
In simplify(), we need to be more careful about operations that can overflow; in particular, add/sub call make_binary() which can overflow in degenerate conditions. This PR adds make_binary_maybe_constant(), which detects overflow for constants and in those cases preserves the expression in `expr` form to avoid overflow.
=> Add make_binary_maybe_constant()

builder/rewrite.h, builder/simplify.cc, builder/simplify_rules.h, builder/test/simplify/simplify.cc
This PR fixes a number of issues with loops of crops:
- We need to check if the loop is empty, and ensure the new crop is also empty in such cases.
- That results in a new select, which we can then simplify away with new rules and logic.
- Strengthen the loop simplification to handle more cases where the proof that the crop bounds overlap is tricky.
=> Fix loop of one crop simplification

builder/node_mutator.cc, builder/pipeline.cc, builder/simplify.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/test/simplify/simplify.cc, builder/test/substitute.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, runtime/depends_on.cc, runtime/depends_on.h, runtime/expr.h, runtime/test/depends_on.cc
Minor fixes to simplify, mostly that improve scalability with large pipelines
- Do constant folding in `constant_bound`
- Strengthen `canonicalize_buffer` by ignoring stride and fold factor of extent 1 dimensions
- Prefer constructing identity transposes in `canonicalize_buffer`, which may turn into `clone_buffer`.
- Add `is_pure` helper. Not actually used by anything in slinky, but might be useful for clients.
- Make `lift_decl_invariants` smarter so we don't duplicate identical buffer mutators for sibling stmts.
- Fix some unnecessary recursive quadratic complexity operations (`substitute_buffer` not needed for crops, `depends_on` not needed to be recomputed in `make_buffer`).
- Fix quadratic block construction in pipeline builder
Fixes #457
=> Simplify improvements

builder/simplify.cc, builder/simplify_exprs.cc, builder/test/simplify/simplify.cc
- Handle `mod` at least in part
- Remove apparently hack/workaround for a bug that seems to have since been fixed that prevents us from learning constant bounds of clamps/mixed `min`-`max`.
=> Tighten `constant_bounds`

builder/pipeline.h, builder/test/copy.cc, builder/test/copy_pipeline.cc
Having to make an `std::vector<char>` is a bit annoying.
=> Add helper to make padded copies

builder/pipeline.cc, builder/replica_pipeline.cc, builder/rewrite.h, builder/simplify.cc, builder/simplify_bounds.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/substitute.h, builder/test/replica_pipeline.cc, builder/test/substitute.cc, runtime/depends_on.cc, runtime/evaluate.cc, runtime/expr.h, runtime/expr_stmt.cc, runtime/print.cc, runtime/print.h, runtime/test/depends_on.cc, runtime/visualize.cc
This PR changes buffer intrinsics (e.g. `buffer_min(buf, dim)`) from being implemented as `call` nodes to `variable` nodes, by adding new fields to `variable`.
This change has a few motivations and implications:
- It is an improvement to #396 and #466, because evaluating a buffer intrinsic now requires evaluating only one node instead of 3. The `BM_buffer_meta` benchmark gets ~5x faster with this branch.
- It loses flexibility, because the `buf` and `dim` arguments to buffer intrinsics are now required to be constants. However, in dozens of places in the code, we asserted those values were `variable` and `constant` nodes anyways, and I doubt we'd ever change that.
- The main motivation for this change is that the simplifier currently treats variables and buffers very differently, with …
=> Replace buffer intrinsics with `variable` fields

builder/pipeline.cc
Currently it generates something like:
```
out.x = loop(serial, [buffer_min(out, 0), buffer_max(out, 0)], 1) {
out = crop_dim(out, 0, [out.x, out.x]) {
intm = crop_buffer(intm, {
[((buffer_min(out, 0) / 2) * 2), ((((((buffer_max(out, 0) + 1) + 2) - 1) / 2) * 2) - 1)],
[buffer_min(out, 1), buffer_max(out, 1)]
}) {
check((((buffer_min(out, 0) / 2) * 2) <= buffer_min(out, 0)))
check((buffer_max(out, 0) <= ((((((buffer_max(out, 0) + 1) + 2) - 1) / 2) * 2) - 1)))
check((buffer_min(out, 1) <= buffer_min(out, 1)))
check((buffer_max(out, 1) <= buffer_max(out, 1)))
intm = allocate(stack, 4, {
{[((buffer_min(out, 0) / 2) * 2), ((((((buffer_max(out, 0) + 1) + 2) - 1) / 2) * 2) - 1)], <>, buffer_fold_factor(intm, 0)},
{[buffer_min(out, 1), buffer_max(out, 1)], <>, buffer_fold_factor(intm, 1)}
}) { …
```
=> Don't produce crop for buffers allocated inside of the statement

builder/pipeline.cc, builder/simplify.cc, runtime/depends_on.cc, runtime/depends_on.h, runtime/test/depends_on.cc
- Fix `lift_decl_invariants` recreating identical `stmt`s
- Both simplify and the pipeline builder had some very similar code to find buffers used in a stmt. Refactor this into a helper `find_buffer_dependencies`.
=> Simplify cleanups and improvements

builder/simplify.cc, builder/substitute.cc
- Don't regenerate matching nodes in mutators
- Don't redundantly mutate crop bounds
- Fix redundant mutation of make_buffer body
=> Fix bugs in simplify

builder/simplify.cc
We might need `info` for more than one stmt
=> Fix another bug in `make_buffer` simplification

builder/slide_and_fold_storage.cc, builder/test/simplify/simplify.cc, runtime/evaluate.cc, runtime/evaluate.h, runtime/test/evaluate.cc
The optional wrapper for values is just overhead, and I want to eliminate dependencies on `symbol_map` where it makes sense.
We do lose the ability to tell if something is set or not in "memory", but we can also do that with msan (assuming we stop `std::vector` from initializing its contents somehow).
=> Use a plain vector instead of `symbol_map` to implement `evaluate`

runtime/buffer.cc, runtime/buffer.h
- Rewrite `for_each_impl_linear` to only use strides when they are actually needed.
- Use folded loops for empty dimensions, so we don't need an extra branch in `for_each_impl_linear`. `for_each_impl_folded` already has a lot of extra control flow, so the extra branch doesn't matter as much.
=> Minor refactoring to avoid benign UB in `for_each_element`

runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.cc, runtime/test/buffer_benchmark.cc
This remove special case from `init_strides` that only exists to make strides "look" better. Some things assert strides are the product of a previous dimension extent and stride, even if the extent is 1 (so the stride is irrelevant to anything). If people want to call other programs with such asserts, they can fix up the strides themselves, but we shouldn't pay the cost to fix them up when they don't matter.
Also:
- Avoid calling `free` on `nullptr` (in case it isn't inline)
- Inline some things in `evaluate` that proved helpful.
=> Small optimizations for very lightweight pipelines

builder/pipeline.h, builder/test/pipeline.cc, runtime/buffer.h
For the lambda version of `func::make`, we currently get two layers of `std::function`: one for `call_stmt::callable`, which is unavoidable, but the other is just a wrapper to change the arguments, and doesn't need to be an `std::function`, which adds some extra overhead.
This PR avoids the inner `std::function`, calling the lambda directly instead.
=> Avoid extra `std::function` layer in `func::make`

runtime/buffer.h
We construct dims explicitly when we actually need them, so this is just extra overhead.
=> Don't default construct `dims_storage`

builder/optimizations.cc, builder/optimizations.h, builder/pipeline.cc, builder/test/pipeline.cc
This changes `alias_buffers` to only alias copies, rather than copies and in-place calls. Doing in-place calls correctly is tricky, and doesn't really need all the complexity of `alias_buffers`. I think it will be better done as a separate pass. We also don't have much that actually relies on this functionality, and in fact a few tests were accidentally relying on it (fixed in this PR), and this should unblock #543.
=> Only alias copies, not calls

base/util.h, builder/optimizations.cc, builder/optimizations.h, builder/pipeline.cc, builder/replica_pipeline.cc, builder/rewrite.h, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/test/elementwise.cc, builder/test/simplify/expr_generator.h, runtime/buffer.cc, runtime/buffer.h, runtime/depends_on.cc, runtime/evaluate.cc, runtime/evaluate.h, runtime/expr.h, runtime/expr_stmt.cc, runtime/print.cc, runtime/print.h, runtime/test/buffer_benchmark.cc, runtime/visualize.cc
- Add a proper "unreachable" code function/macro
- Optimize `init_strides` by maintaining a sorted list of dimensions
- Compute buffer size in `init_strides`, so allocation uses don't need to call both functions
- Add some guesses to likely nodes types in evaluate
- Lift growing the context "memory" out of loops
- Tweak inlining of evaluate implementations
- Remove checks later, so the second `simplify` can see them
- Add `canonicalize_nodes`
- Tweaks to `for_each_element`
=> Small optimizations

base/thread_pool.cc, builder/simplify_exprs.cc, builder/slide_and_fold_storage.cc, builder/test/pipeline.cc, builder/test/pyramid.cc, runtime/evaluate.cc, runtime/expr.h, runtime/expr_stmt.cc, runtime/print.cc, runtime/test/evaluate.cc, runtime/test/evaluate_benchmark.cc
This reverts commit 0cccdc544a9798d22267606aeb5f49255708531b.
=> Revert "Remove pipeline parallelism (#555)"

builder/optimizations.cc, builder/optimizations.h, builder/pipeline.cc, builder/test/elementwise.cc, builder/test/pipeline.cc, runtime/expr.h
This recovers functionality lost in #548
=> Alias inputs and outputs of calls that can be performed in-place

builder/optimizations.cc, builder/test/copy_pipeline.cc
Previously, if we tried to alias a buffer with padding that was allocated outside of a loop, but used inside a loop, we would try to use the cropped loop buffer to expand the bounds of the allocation.
This adds a test that was failing, and the fix for that test.
=> Handle padded aliases inside loops

builder/rewrite.h, builder/simplify.cc, builder/simplify_rules.h, builder/test/simplify/simplify.cc
- Strengthen `constant_adder` to avoid missed cancellations
- Add some `min`/`max`/`select` rules
- Allow loop bodies to assume the bounds are non-empty
=> Small simplify improvements

builder/optimizations.cc, builder/test/cannot_alias.cc
This fixes bugs where we incorrectly alias copy dsts to copy srcs when the copy src is bigger than the dst.
=> Check that copy dsts are big enough to be aliases of copy srcs

builder/optimizations.cc, builder/substitute.cc, builder/test/optimizations.cc
We had a terrible bug where if we found two calls with the same arguments (which can happen due to aliasing and reusing allocations), we thought they were equivalent, and canonicalized them.
However, `match` did not check if `call_stmt::target` was equal, which caused us to possibly call a different function.
This also fixes `fuse_siblings` to recursively mutate. Fusing a sibling can reveal new fusions in the result that we missed.
=> Fix `canonicalize_nodes` for similar-looking calls

builder/optimizations.cc, builder/optimizations.h, builder/test/optimizations.cc
#566 was incomplete, an std::function might point to the same function pointer, but have a different capture state. This just gives up on attempting to canonicalize calls to avoid these problems.
=> Don't rely on `match` for `call_stmt`

builder/optimizations.cc, builder/pipeline.cc, builder/test/copy_pipeline.cc
Constants need to be outside copy destinations to be aliased, this PR adds a test for that and moves constants outermost.
=> Fix broadcasts of constants

builder/pipeline.cc
This is a subset of #570. I think maybe we should just submit this change, which allows people to define constants that are empty buffers as placeholders.
=> Allow unconstrained input bounds

builder/optimizations.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/substitute.h, runtime/evaluate.cc
- Don't create symbols for sentinel loop in `slide_and_fold_storage`
- Add `constant_buffer` handler for `substitute`
=> Minor fixes

runtime/evaluate.cc, runtime/test/evaluate.cc
This fixes a long-standing subtle bug: evaluating the bounds of unshadowed crops *after* assigning the new buffer to the context.
This is not correct because if the bounds use that symbol, they'll use the new buffer that could shadow something from the bounds expressions.
We haven't hit this bug yet because we currently aren't very aggressive about re-using symbols, so actually shadowing something like this was rare.
This should also be a bit of an optimization, because we previously saved and restored the buffer state even in the unshadowed case, which isn't necessary.
=> Fix evaluate for unshadowed crops

builder/pipeline.cc
They are handled in almost the same way to "special" allocations (really need a better name for these, maybe "constrained"?), due to this code is fairly similar but not quite, I'm not sure if it's worth it to try to make it more general. 
This seems to be pretty effective way to do it, for one of the larger pipelines the depth went from 313 to 6!
There are also some somewhat related refactorings.
=> Better layout for the constant buffers

base/thread_pool.h, runtime/evaluate.cc
This allows working around an issue where work that had already started prior to adding more threads to the thread pool had an underestimate of how many workers the thread pool contains. `expect_workers` allows the calling program to say how many workers will be available, even if that many are not running yet.
=> Add `expect_workers` API

runtime/evaluate.cc, runtime/test/evaluate_benchmark.cc
This might or might not be an optimization, but it avoids msan flagging uninitialized memory use. I thought it wouldn't do that, because it doesn't branch/do anything with the uninitialized memory (just read it and write it somewhere else), but apparently not.
=> Don't evaluate the loop variable in the closure

builder/pipeline.h, builder/test/BUILD, builder/test/auto_stack_threshold.cc, builder/test/context.cc, builder/test/pipeline.cc, builder/test/visualize/softmax_split_0.html, runtime/evaluate.cc, runtime/evaluate.h, runtime/print.cc, runtime/stmt.h
This PR makes it so by default, buffer allocations are placed on the stack if they are small, as determined by a parameter `eval_config::auto_stack_threshold`.
=> Add `memory_type::automatic`

base/test/thread_pool.cc, base/test/thread_pool_benchmark.cc, base/thread_pool.h
This also adds some new functionality to enable thread-local parallel for state, but it is currently not enabled (we still use `K = 1` for `thread_pool::parallel_for`).
=> Refactor parallel_for implementation to a helper class

runtime/evaluate.cc, runtime/stmt.h
This PR fixes a few things:
- Initializes the context used by a parallel for loop body once per thread instead of once per loop iteration. This basically means duplicating `thread_pool::parallel_for`'s implementation, so we can add some code that runs outside the task loop in each worker.
- While working on this, I noticed that we execute the closure for parallel loops twice. This PR fixes that.
=> Initialize the closure once per thread instead of once per context

base/BUILD, base/function_ref.h, runtime/buffer.cc, runtime/buffer.h
This PR changes `for_each_element` et al to use type erased `function_ref` (placeholder for C++26 `std::function_ref`) callbacks in its implementation. This reduces the code size of clients that use many `for_each_element` calls.
Surprisingly, it's hard to even measure much performance impact of this PR, and I think there might be more performance improvement opportunities enabled by this change too (e.g. we could precompute function pointers to implement `for_each_loop`).
=> Move for_each_element implementation to buffer.cc

runtime/buffer.cc, runtime/buffer.h
- We can directly call explicitly instantiated templates, instead of doing a dynamic dispatch
- Instantiate BufsSize = 4 case
=> Minor `for_each_element` optimizations

base/span.h, runtime/buffer.cc, runtime/buffer.h, runtime/test/buffer.cc, runtime/test/buffer_benchmark.cc
I've now invested a silly amount of effort in this function, and I'm hoping this is basically as good as it can get, barring the possibility that we change the definition of `raw_buffer` in some way that affects this. This makes it 10-30% faster, depending on the benchmark.
The major change here is to use function pointers stored in the `for_each_loop` stack, instead of flags + a dispatcher function. Also:
- Add the `constexpr` `Extent` template parameter of our `std::span` clone, and use it to avoid passing an unused parameter around.
- Avoid changing the type of rank/dim indices, which adds some overhead.
- A bunch of other minor simplifications and cleanups.
My ultimate goal was to get to the point where we could use computed gotos and implement this without function calls at all. …
=> Optimize `for_each_element`

base/BUILD, base/function_ref.h, base/thread_pool.cc, base/thread_pool.h, builder/node_mutator.h, builder/optimizations.cc
This was a speculative optimization for the thread pool. It didn't do much in my case, but it's a good change anyways.
=> Use `function_ref` where appropriate

runtime/buffer.cc, runtime/test/buffer.cc
Currently, we evaluate folded loops very simply, by evaluating each iteration independently. This has high overhead, especially for `for_each_contiguous_slice` where the folded dimension is contiguous.
This PR adds logic to call the callbacks on linear chunks at a time when possible:
- Between folding boundaries
- When not crossing a buffer boundary
=> Optimize for_each_element folded loops

runtime/buffer.cc, runtime/test/buffer.cc
#602 allowed folded innermost dimensions that are contiguous to be passed to `for_each_contiguous_slice` callbacks, but not non-innermost dimensions. This PR fixes that.
It is a small regression in unaffected cases due to the parameter being passed through each loop implementation function even when it isn't used.
=> Support contiguous folded dimensions that aren't the innermost loop

builder/pipeline.cc, builder/test/softmax.cc
Apparently, the test which checked compute_at was disabled and was failing at head after I enabled it. The issue is that we first were visiting the inner loop which might violate the assumption that the function are added in the order of their occurance in the final IR (this is important so we can merge lifetimes correctly).
=> Fix the order of the function during the IR construction.

builder/pipeline.cc, builder/test/softmax.cc
This PR the part which produces allocate nodes from ```build``` to ```make_loop```, which makes it more logical because allocations are tied to the loop level and make_loop has view of  all statements included in it. In order to make code simpler, we now start IR construction by creating a "root" loop in which case we only produce the body of the "loop", but not the crops or actual loop.
(Technically, this got broken by #608, but since that was the fix ```compute_at``` which wasn't working, it's fair to say that ```store_at``` didn't work either by transitivity)
=> Fix store_at and add a test for it

runtime/buffer.h, runtime/test/buffer.cc
This allows calling `at` and `address_at` with a value `slice` that essentially skips the dimension. This is useful for writing func implementations where you want to get a pointer to the beginning of a region to process that is the min in some dimensions (that aren't the training dimensions) and not others.
It's a bit tricky what this means for folded dimensions, because the base doesn't point to the min of folded dimensions. I think the right thing to do is just skip these dimensions, because the code is likely to add the offset for this dimension later.
=> Add `slice` constant for use with `at`/`address_at`

builder/slide_and_fold_storage.cc
We start with a bogus loop and if there are call_stmt/copy_stmt at the root level, we might end up with useless semaphores.
=> Initialize loop_info::max_workers to 0 by default to avoid creating useless semaphores at the root level

builder/pipeline.cc, builder/test/softmax.cc
This actually improves one of the few tests which uses store_at (we could probably use more tests with store_at though).
=> Produce crops for all transitively used buffers inside of the loop body

runtime/expr_stmt.cc
This is what visit(allocate*) is doing too.
=> Check if stride is defined before visiting

builder/pipeline.cc, builder/test/pipeline.cc, builder/test/softmax.cc
Previously, we would produce crop_buffer-s for all buffers even if they are  allocated inside of the body of the crop. In this case we really need only buffer metadate, so make_buffer is enough.
This also regresses back the previosly improved test. I think we need to teach slide_and_fold_storage to take bounds from make_buffer as well to fix it -- will fix in follow up CL.
=> A more targeted store_at test and fix for it

builder/pipeline.cc, builder/pipeline.h
The idea is to do something like:
```
f->output->store_at({f, var()});
```
I'm not sure it's a best interface, but it is concise -- open to other suggestions.
=> Add a way to schedule a buffer to be stored at the same level it's computed at

builder/simplify.cc, builder/substitute.cc, builder/substitute.h, builder/test/simplify/simplify.cc
- Substitute no-op crops before mutating the body instead of after
- If two nested crops are the same, just re-use the outer one.
=> Improve simplification of crops

builder/optimizations.cc, builder/test/checks.cc, builder/test/context.cc, runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.h, runtime/test/buffer.cc, runtime/test/buffer_benchmark.cc
- Remove `fill`, because it is equivalent to `copy` with a scalar buffer as the `src`.
- Change the padding argument of `copy` and `pad` to be a buffer instead of a scalar value. This allows the padding to vary across the output.
This PR is a fairly significant performance regression for some cases of `fill` and `copy` (`fill`/`copy` is 1.2-2x slower for broadcasting copies, only slightly slower for dense copies). It is also an improvement in some cases (copying from folded dense dimensions).
However, we need the extra flexibility enabled by this, and I believe we could recover the performance loss, but it would require handling quite a few cases ({padding, no padding} x {src broadcast, src dense, src strided} x {pad broadcast, pad dense, pad strided}). I think this is reasonably doable, …
=> Rewrite copy, pad, fill to always take buffers instead of scalar values

base/thread_pool.h, builder/node_mutator.cc, builder/optimizations.h, builder/pipeline.h, builder/replica_pipeline.cc, builder/slide_and_fold_storage.cc, builder/substitute.cc, builder/test/aligned_producer.cc, builder/test/cannot_alias.cc, builder/test/context.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/elementwise.cc, builder/test/pipeline.cc, builder/test/simplify/simplify.cc, builder/test/softmax.cc, runtime/depends_on.cc, runtime/expr_stmt.cc, runtime/pipeline.cc, runtime/test/buffer.cc, runtime/test/buffer_benchmark.cc, runtime/test/evaluate.cc, runtime/visualize.cc
- Replace `testing::Values(false, true)` with `testing::Bool()`
- Run clang-format on everything
=> Minor cleanups

builder/node_mutator.cc, builder/optimizations.cc, builder/pipeline.cc, builder/pipeline.h, builder/replica_pipeline.cc, builder/simplify.cc, builder/substitute.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/elementwise.cc, builder/test/pipeline.cc, builder/test/replica_pipeline.cc, builder/test/substitute.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html, builder/test/visualize/padded_stencil_2.html, runtime/depends_on.cc, runtime/expr_stmt.cc, runtime/print.cc, runtime/stmt.h, runtime/test/depends_on.cc
This picks up where #633 left off and enables padding to be buffers in the pipeline API as well.
Padding can now be computed by another stage in the pipeline, and does not need to be a scalar value. It is now essentially the same as any other input to any other pipeline stage.
=> Allow padding of copies in pipelines to be a buffer instead of a scalar

builder/simplify.cc, builder/test/simplify/simplify.cc, runtime/depends_on.cc, runtime/evaluate.cc, runtime/expr.h, runtime/test/depends_on.cc, runtime/test/evaluate.cc
Currently, we allow crops to have undefined bounds, which means there is no crop at that bound.
We also allow things like `select(x, expr(), y)` in crop bounds, and that means that the crop should do nothing in the case `x` is true. This is a headache to support well.  This PR removes this, so `expr()` would need to be a `buffer_min` expression instead.
Also, don't capture undef vars in closures
=> Fix undefined expressions in crop bounds and closures

builder/test/simplify/simplify.cc, runtime/print.cc
- Set the default print context in the simplify test to make failures easier to read
- Tweak printing `stmt` so the newline goes before the indentation, rather than at the end of each line
=> Small print tweaks

base/BUILD, base/atomic_wait.h, base/test/BUILD, base/test/atomic_wait_benchmark.cc
Backport C++20 atomic_wait https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0514r3.pdf
P.S. the backported implementation is guarded by __cpp_lib_atomic_wait, if this feature is available the functions
simply call the corresponding std:: implementations.
=> Backport C++20 atomic_wait 

base/arithmetic.h, base/test/arithmetic.cc, base/test/arithmetic_benchmark.cc
- Add `euclidean_div_positive_divisor` to simplify some logic
- Use `a % b` instead of computing it. This is a lot faster with clang, but doesn't affect gcc.
=> Add `euclidean_div_positive_divisor` and optimize

builder/pipeline.cc
This reduces number of crops for some of the pipelines a lot and makes compilation much faster.
=> Only add crops which can be affected by loop's crop_dim

builder/simplify_rules.h, builder/test/simplify/rule_tester.h, builder/test/simplify/simplify.cc
- Canonicalize which constant we pull from both sides of a min/max. This fixes an infinite loop bug.
- Add some rules that simplify expressions from pyramid pipelines.
=> Fix simplify issues for pyramid heavy pipelines

builder/optimizations.cc, builder/substitute.cc, builder/substitute.h, builder/test/copy_pipeline.cc, builder/test/substitute.cc
`substitute_buffer` would replace buffer values with undef if the value wasn't defined, which is incorrect for the way the crop visitors were using it in aliasing.
This adds an optional parameter to `substitute_buffer` that indicates unspecified values should be taken from a different buffer, instead of left as undef.
At first I tried to fix this by just substituting the buffer values we want in the crop handler. However, this doesn't work, because crop doesn't know how many dimensions the buffer has, so it can't fully populate the `dims` with the correct values.
=> Fix crop handling for aliasing

builder/test/funcs.h, builder/test/stencil_pipeline.cc
The bounds of input buffers in slinky are not guaranteed to be anything useful or relevant to the pipeline.
=> Don't rely on the bounds of the input buffer for reduction size

base/test/thread_pool_benchmark.cc, runtime/evaluate.cc, runtime/test/evaluate_benchmark.cc
This avoids all the workers attempting to cancel the pending workers, which requires locking the thread pool mutex. Only the first worker to cancel actually does the cancel.
This also makes the benchmarks for parallelism more useful, which revealed this as a problem (with some extra tracing hacked in).
=> Only cancel pending tasks once

base/BUILD, base/arithmetic.cc, base/arithmetic.h, base/test/BUILD, base/test/arithmetic.cc, builder/rewrite.h, builder/simplify_bounds.cc, builder/simplify_rules.h, builder/test/simplify/simplify.cc
This PR adds the `staircase` pattern helper, which makes it a lot less annoying to handle the various special cases for rules that want to match things like `((x + a)/b)*c`, where a could be 0, and b or c could be 1.
=> Add rules and logic to handle negative division numerators

builder/test/copy_pipeline.cc
This reduces the time to run the `copy_pipeline` test by ~20%.
=> Reduce padded_copy test combinations

base/thread_pool.cc, base/thread_pool.h, builder/test/tile_area.cc, runtime/evaluate.cc
This makes every queued task in the thread pool a `parallel_for<>` object instead of a simple task. (Tasks are now loops with `n = 1`.)
This eliminates the need for the `cancel` mechanism, which was clunky and high overhead. Now, we can simply see if any work remains *before* starting to work on a task instead of after, which eliminates a lot of unneeded worker tasks, especially in the case of nested parallel loops.
=> Every task is a loop in the thread pool

base/thread_pool.cc, base/thread_pool.h
#671 has a theoretical bug, if the main thread working on a parallel for loop does not complete the loop, `work_on_loop` returns false, but the loop might not be done yet and we need to wait for it.
I've never seen it actually cause a test to fail, but it definitely seems like a bug.
This does a related cleanup: by moving all of the loop completion logic to be inside `thread_pool::run`, it eliminates a use of `wait_for` from the thread pool public API, which makes the thread pool API more implementable by other thread pools. There is still a use of `wait_for` in the evaluator logic, but, one step at a time.
=> Fix not waiting for loops that were not completed by main thread but still not done

builder/rewrite.h, builder/simplify_rules.h, builder/test/BUILD, builder/test/rewrite.cc, builder/test/simplify/rule_tester.h, builder/test/simplify/simplify.cc, runtime/expr.h, runtime/expr_stmt.cc
This PR makes it possible to optionally match something in a pattern, with a default value if not matched. This allows reducing the duplication in many simplifier rules, which makes the simplifier faster and smaller.
This PR is a subset of #662, removing many of the optional rule rewrites for a later PR.
=> Add optional pattern matching in the rewriter

builder/optimizations.cc
This is a significant speed-up for the large pipeline.
=> Only run bound_of if the bounds depend on the loop var

builder/optimizations.cc, builder/simplify.cc
- Remove self bounds from `mutate_crop_bounds`. Each thing in this set is expensive, and this one seems to be unnecessary.
- Use `match` instead of `prove_true` in `remove_pure_dims`, `prove_true(x == y)` is likely overkill after simplification
- We don't need to check `min(x, y)`/`max(x, y)`  *and* `x`, `y`, and for redundant-ness
=> Optimize simplify usages

builder/optimizations.cc, builder/test/visualize/padded_stencil_0.html, builder/test/visualize/padded_stencil_1.html
A specific case I was looking at was a transpose which could have been aliased to the output, but output had min explicitly set to 0, so after substituion the call to alias_compatible would fail despite both target and source having bounds expressed in terms of output bounds.
=> Try alias_compatible with and without substitution of the target

base/ref_count.h
These may be useful for some client implementations of `thread_pool`.
=> Add `ref_count<T>::take` and `::assume`

apps/performance.cc
Include immintrin.h only on x86_64.
This fixes the build on arm64.
=> Include immintrin.h only on x86_64

base/test/thread_pool.cc, base/thread_pool_impl.cc, base/thread_pool_impl.h
This helper is useful when trying to use `thread_pool_impl` to wrap an existing thread pool. This is similar to `run_worker`, but instead of waiting on the condition variable when there is no work to do, it just returns. This is useful to call from a scheduled task in another thread pool that we want to work on the `thread_pool_impl` queue instead.
=> Add `thread_pool_impl::work_until_idle`

base/test/thread_pool.cc, base/thread_pool_impl.cc
Not all of the workers may be started when `thread_count` is called, leading to an incorrect number of threads being reported.
=> Set expected workers in thread pool's constructor

builder/optimizations.cc, builder/test/cannot_alias.cc
We can't reallocate constants with padding like we can intermediate allocations.
=> Treat constants as inputs, so we don't try to reallocate them

builder/node_mutator.cc, builder/optimizations.cc, builder/pipeline.cc, builder/pipeline.h, builder/simplify.cc, builder/substitute.cc, builder/test/cannot_alias.cc, builder/test/context.cc, builder/test/context.h, builder/test/copy.cc, builder/test/copy_pipeline.cc, builder/test/optimizations.cc, builder/test/stencil.cc, builder/test/substitute.cc, runtime/buffer.cc, runtime/buffer.h, runtime/evaluate.h, runtime/expr_stmt.cc, runtime/stmt.h, runtime/test/depends_on.cc
This allows one to define pipelines with copies in them that might alias to another buffer, but if they don't, to call a user defined implementation of copy instead of `slinky::copy`.
This provides a way to optimize special cases of copies, such as transposes that affect dimensions with a small and/or fixed stride.
=> Allow copy funcs to have a custom copy implementation

.github/workflows/ci.yml, MODULE.bazel, base/BUILD, base/thread_pool_impl.cc, base/thread_pool_impl.h, base/thread_synchronization.h
This adds an option `--define slinky_use_absl_synchronization=true` to the build, which will use `absl::Mutex` instead of `std::mutex`.
=> Provide option to use absl synchronization primitives for thread pool

builder/optimizations.cc, builder/test/stencil.cc, builder/test/stencil_pipeline.cc
And modify `is_copy` to be able to handle this case, by looking for constant bounds, rather than constants.
=> Add tests of variable stride/dilation stencils

builder/optimizations.cc, builder/test/copy.cc, builder/test/copy_pipeline.cc
This other copy formulation is simpler and easier to understand, but, it doesn't always work. We can at least use it when we can.
This PR also adds some tests that don't require this change, but were easier for me to debug in a different way with this change.
=> Use simpler `is_copy` result when we can

builder/optimizations.cc, builder/test/cannot_alias.cc
This PR fixes a bug where if an output is also used as an input to another stage, we would compute those in place, and corrupt the output with the other stage's output.
=> Fix alias_in_place bug

runtime/buffer.h, runtime/test/buffer.cc
When there are broadcasted buffers between the mismatched dimensions, we failed to catch it because we allow the intervening broadcasts to fuse.
=> Fix fuse_contiguous_dims case

builder/test/optimizations.cc, builder/test/simplify/simplify.cc, builder/test/substitute.cc, runtime/test/depends_on.cc
This makes subsequent changes to `call_stmt::make` less noisy
=> Refactor `call_stmt::make` calls uses in tests

builder/simplify.cc
This allows user defined functions to be constant folded.
I think this also makes more sense: we only need to disallow evaluating functions that otherwise appear evaluatable (no non-constant arguments).
=> Negate `can_evaluate`
