dsharlet/slinky

builder/pipeline.h
builder/pipeline_test.cc

https://github.com/dsharlet/slinky/pull/39 got landed before I had a chance to push this commit to it :-)

Make func::make understand lambdas

---

runtime/buffer.cc
runtime/buffer.h

This might be the last of my obsessive optimization of `for_each_contiguous_slice`...

Get begin from dim

---

builder/copy_test.cc
builder/infer_bounds.cc
builder/optimizations.cc
builder/pipeline.cc
builder/pipeline.h
builder/pipeline_test.cc

This isn't something we immediately needed, but it is good at exercising codepaths that should work.

Add `func::make_stack`

---

runtime/buffer.h

Doesn't really seem to move the needle much (I verified that it remove the calls to stkchk)...
before:
```
Benchmark                                            Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------------
BM_for_each_contiguous_slice/64/16/1              41.0 ns         41.0 ns     65728123 bytes_per_second=45.0949Gi/s
BM_for_each_contiguous_slice/64/4/4               41.1 ns         41.1 ns     70735311 bytes_per_second=44.9251Gi/s
BM_for_each_contiguous_slice_multi/64/16/1        62.4 ns         62.4 ns     45553978 bytes_per_second=59.2437Gi/s
BM_for_each_contiguous_slice_multi/64/4/4         60.2 ns         60.2 ns     45854848 bytes_per_second=61.3731Gi/s …
```

Disable stack-protector for alloca() fns

---

runtime/buffer.cc
runtime/buffer_benchmark.cc

There were even more bugs like those fixed in #116. This clearly calls for a helper function.

Benchmark fixes

---

.gitignore
builder/simplify.cc
builder/simplify_test.cc

Added symbol_info to references for a simplifier

---

runtime/buffer.h

I was trying to put a buffer in an array, and was foiled by the inability to move buffers.

Add move assignment operator and move constructors to buffer

---

builder/pipeline_test.cc

From https://github.com/dsharlet/slinky/issues/49#issuecomment-1967937852

Add test from the issue #49

---

runtime/print.cc
runtime/print.h

Basically just the enum values for now; this will allow easier recycling of the code in (eg) https://github.com/dsharlet/slinky/pull/147

Add to_string() for [some] of print.h

---

builder/pipeline_test.cc

Fix replica golden test on windows

---

runtime/buffer.cc

We don't really support broadcasted outputs well yet anyways, but this at least makes it work for now.

Fix infinite loops when broadcasts are the only dimension in the output of a copy/fill/pad

---

README.md
builder/BUILD
builder/bazel_util.h
builder/pipeline_test.cc
builder/test_util.h
builder/visualize/concatenate_0.html
builder/visualize/concatenate_1.html
builder/visualize/padded_stencil_0.html
builder/visualize/padded_stencil_1.html
builder/visualize/padded_stencil_2.html
builder/visualize/parallel_stencils_0.html
builder/visualize/parallel_stencils_1.html
builder/visualize/parallel_stencils_2.html
builder/visualize/stencil_chain_split_0.html
builder/visualize/stencil_chain_split_1.html
builder/visualize/stencil_chain_split_2.html
builder/visualize/stencil_split_0.html
builder/visualize/stencil_split_1.html
builder/visualize/stencil_split_2.html
builder/visualize/stencil_split_3.html
runtime/visualize.cc
runtime/visualize.h

- Generate the visualizations in a committed repo path
- Add (golden) tests of the generated visualizations
- Link (via https://html-preview.github.io/) to the visualizations in the readme.
- Some visualizations were broken because they used abs, not defined in the generated html

Visualization testing and links

---

builder/simplify.cc
builder/visualize/concatenate_0.html
builder/visualize/concatenate_1.html
builder/visualize/padded_stencil_0.html
builder/visualize/padded_stencil_1.html
builder/visualize/padded_stencil_2.html
builder/visualize/parallel_stencils_0.html
builder/visualize/parallel_stencils_1.html
builder/visualize/parallel_stencils_2.html
builder/visualize/stencil_chain_split_0.html
builder/visualize/stencil_chain_split_1.html
builder/visualize/stencil_chain_split_2.html
builder/visualize/stencil_split_0.html
builder/visualize/stencil_split_1.html
builder/visualize/stencil_split_2.html
builder/visualize/stencil_split_3.html
runtime/visualize.cc

- Arithmetic needs to be euclidean to work properly
- Stride 0 dimensions are weird, don't make them unnecessarily

Minor visualization fixes

---

runtime/buffer.h
runtime/buffer_benchmark.cc
runtime/buffer_test.cc

This is a useful helper for writing func callback implementations

Add `fuse_contiguous_dims` helper

---

builder/test/pipeline.cc

I used this test while working on bounds inference, but forgot to include it in the PR itself. I think this is useful to have as it makes sure we don't do substitute too intensely.

Add a 4-level pyramid test

---

builder/simplify_exprs.cc

We now fold 3 levels of upsampling instead of 1.

Add more rules that help bigger pyramids fold

---

builder/rewrite.h
builder/simplify_bounds.cc

There are some expressions that are very hard to simplify that also fail to produce tight bounds due to limitations of interval arithmetic. This PR works around this by adding some special cases to such expressions in `bounds_of`.
This finds the fold factors in the 4 level pipeline. However, doing so causes asserts regarding cropping and folding to fail (See #40 and #59 for more information). "Fortunately", we don't actually do this folding on main, because we can only get this folding if we hack `where_true` to work in this case.

Tighten bounds of some subs with patterns

---

builder/simplify_bounds.cc
builder/simplify_exprs.cc
builder/test/simplify.cc

- Steal more rules from Halide
- Clean up some rules

More simplifier rule work

---

.github/workflows/ci.yml
builder/test/BUILD
builder/test/pipeline.cc
builder/test/pyramid.cc

More strict build environments complained about these things.

Minor header and dep cleanups/fixes

---

builder/test/BUILD
builder/test/pyramid.cc
builder/test/softmax.cc
runtime/util.h

This is a pipeline with mildly interesting re-use patterns, and is a common example of something that slinky should be able to help with easily.

Add test that does softmax

---

runtime/buffer.cc

These have accumulated quite a bit of redundancy in the last round of adding functionality to this.

Clean up make_for_each_slice_dims

---

runtime/buffer.h
runtime/test/buffer.cc

This speeds up the BM_fill_batch_dims benchmark by almost 2x. Related to #275

Speed up slices especially of trailing dims

---

builder/test/pipeline.cc
runtime/evaluate.cc
runtime/expr.h
runtime/print.cc

This makes it possible to have a `free` function in slinky code.

Minor cleanup to allocations

---

builder/pipeline.cc
builder/slide_and_fold_storage.cc
builder/test/softmax.cc
builder/test/visualize/parallel_stencils_1.html

This fixes the softmax with copy from https://github.com/dsharlet/slinky/pull/296

Use inferred bounds for loop bounds

---

builder/test/copy_pipeline.cc

This test should alias, but #313 prevents it. This test also should be able to fold the buffer when not broadcasted @vksnk .

Add an optional broadcast of an internal buffer

---

builder/pipeline.cc
builder/rewrite.h
runtime/expr.h
runtime/expr_stmt.cc
runtime/test/buffer_benchmark.cc

- Fix build problems on 32-bit targets
- Fix warning when asserts are disabled
- Minor benchmark cleanups

Build cleanups

---

builder/optimizations.cc
builder/test/copy.cc

Optimised copy for downsample

---

builder/pipeline.cc
builder/slide_and_fold_storage.cc
builder/test/softmax.cc
builder/test/visualize/padded_stencil_2.html
builder/test/visualize/parallel_stencils_0.html
builder/test/visualize/parallel_stencils_1.html
builder/test/visualize/parallel_stencils_2.html
builder/test/visualize/softmax_split_1.html
builder/test/visualize/softmax_split_4.html
builder/test/visualize/stencil_chain_split_serial_split_1.html
builder/test/visualize/stencil_chain_split_serial_split_2.html
builder/test/visualize/stencil_split_1.html
builder/test/visualize/stencil_split_2.html
builder/test/visualize/stencil_split_3.html

I'm pretty convinced now that it's a safe thing to do and helps a lot with simplifications needed for folding. The new test doesn't fold at main, but folds now.

Use actual bounds when we store information about the loop

---

builder/simplify_exprs.cc
builder/test/simplify.cc

I don't have super high confidence in these rules. I've fuzzed them a ton, with intentionally broken rules to make sure there is coverage. It's not the kind of thing I want to write a positive test for, because coming up with the correct expression manually is difficult too. The way I've been checking those is tedious.

Add rules for proving expressions are monotonic

---

builder/simplify_exprs.cc
builder/test/simplify.cc

@dsharlet  thanks for the help with finding these rules. I wasn't sure if I need to add some specific tests or fuzzer should cover this?

Various simplifier rules to help with folding

---

builder/rewrite.h
builder/simplify.cc
builder/simplify.h
builder/simplify_exprs.cc
builder/slide_and_fold_storage.cc
builder/test/simplify.cc

This PR makes the simplifier more capable of simplifying expressions based on bounds relationships, by using constant bounds more, and strengthening `constant_bounds`.

Strengthen simplification and minor improvements

---

builder/optimizations.cc
builder/optimizations.h
builder/pipeline.cc
builder/simplify_bounds.cc
builder/test/cannot_alias.cc
builder/test/copy_pipeline.cc
builder/test/pipeline.cc
builder/test/simplify.cc
builder/test/visualize/padded_stencil_0.html
builder/test/visualize/padded_stencil_1.html
builder/test/visualize/padded_stencil_2.html
builder/test/visualize/parallel_stencils_0.html
builder/test/visualize/parallel_stencils_1.html
builder/test/visualize/parallel_stencils_2.html
builder/test/visualize/softmax_split_0.html
builder/test/visualize/softmax_split_1.html
builder/test/visualize/softmax_split_4.html
builder/test/visualize/stencil_chain_split_serial_split_0.html
builder/test/visualize/stencil_chain_split_serial_split_1.html
builder/test/visualize/stencil_chain_split_serial_split_2.html
builder/test/visualize/stencil_split_0.html
builder/test/visualize/stencil_split_1.html
builder/test/visualize/stencil_split_2.html
builder/test/visualize/stencil_split_3.html
runtime/buffer.h

This PR allows folded buffers to alias when we can prove it is safe.

Alias folded buffers when possible

---

builder/simplify_rules.h
builder/test/simplify/simplify.cc

More simplify rules

---

builder/optimizations.cc
builder/slide_and_fold_storage.cc
runtime/evaluate.cc

- Fix `fix_buffer_races`, broken since shadowing.
- Fix `slide_and_fold_storage` to not rewrite data parallel loops (with one stage) to be serial.
Currently, this just deletes fold factors from data parallel loops. Still TODO how to handle this better.

Data parallel loop fixes

---

base/chrome_trace.cc
base/chrome_trace.h

This makes tracing more efficient, which is important when doing many fine grained traces.

Make multithreaded tracing more efficient

---

builder/pipeline.cc
builder/test/visualize/softmax_split_0.html
builder/test/visualize/softmax_split_1.html
builder/test/visualize/softmax_split_4.html

This reverts commit d3370ca28e39fa6ece6daeef6c6f77ece972c6b6.

Revert "Fix sanitizer ordering issues (#415)"

---

builder/simplify.cc
builder/test/simplify/simplify.cc
builder/test/visualize/padded_stencil_2.html
builder/test/visualize/parallel_stencils_0.html
builder/test/visualize/parallel_stencils_1.html
builder/test/visualize/parallel_stencils_2.html
builder/test/visualize/softmax_split_0.html
builder/test/visualize/softmax_split_1.html
builder/test/visualize/softmax_split_4.html
builder/test/visualize/stencil_chain_split_serial_split_1.html
builder/test/visualize/stencil_chain_split_serial_split_2.html
builder/test/visualize/stencil_chain_split_serial_split_3.html
builder/test/visualize/stencil_chain_split_serial_split_4.html
builder/test/visualize/stencil_split_1.html
builder/test/visualize/stencil_split_2.html
builder/test/visualize/stencil_split_3.html

Now that we don't allow shadowing, we can always remove clones

---

builder/optimizations.cc

- Vector iterators could be invalidated in nested visits
- Don't try to validate implicit broadcasts, we don't know which dimension they came from

Bug fixes found in huge pipelines

---

builder/simplify.cc
builder/simplify_rules.h
builder/test/simplify/simplify.cc

- This adds the ability to learn bounds from conditions, and uses it to help simplify selects.
- A bunch of new rules, mostly for selects and and/or of comparisons.

More simplification

---

base/chrome_trace.cc
base/chrome_trace.h

I think this might be very helpful to see why multithreaded code is slow.

Trace CPU time too

---

base/thread_pool.h

Only cancel once

---

runtime/test/buffer.cc

These fuzz tests were testing the same thing repeatedly :(

Fix buffer fuzz tests

---

builder/simplify.cc
builder/simplify_rules.h
builder/test/pipeline.cc
builder/test/simplify/simplify.cc
builder/test/visualize/padded_stencil_2.html

And a few more improvements:
- More rules for min/max related to loops
- Substitute crops before dropping them

Handle added constants with a mutator instead of rules

---

builder/pipeline.cc

When using constant buffers in pipelines, we currently get some checks like:
```
check(0 <= buffer_min(constant, 0));
check(buffer_max(constant, 0) <= 9);
```
But `constant` is an actual buffer we have at build time, so we should be able to statically prove or disprove these checks.
This PR enables that by using the actual buffer to get the min/max, instead of just calling `buffer_min`/`buffer_max`.

Use the actual buffer metadata for checks instead of buffer calls

---

base/thread_pool.cc
builder/simplify_exprs.cc
builder/slide_and_fold_storage.cc
builder/test/pipeline.cc
builder/test/pyramid.cc
runtime/evaluate.cc
runtime/expr.h
runtime/expr_stmt.cc
runtime/print.cc
runtime/test/evaluate.cc
runtime/test/evaluate_benchmark.cc

This strategy for pipeline parallelism isn't very useful, and it is an obstruction to other parallelism improvements.

Remove pipeline parallelism

---

runtime/evaluate.cc

Enter wait_for only if the loop is not done yet.

Enter wait_for only if loop is not done yet

---

builder/substitute.cc
builder/test/pipeline.cc

Thanks @dsharlet for the help with this PR!

Make match for call_stmt act as same_as

---

builder/optimizations.cc
builder/optimizations.h
builder/pipeline.cc
builder/test/optimizations.cc
runtime/stmt.h

Add initial support for removing pure dimensions.

Add initial support for removing pure dimensions

---

builder/simplify.cc
builder/test/simplify/simplify.cc
runtime/expr.h
runtime/expr_stmt.cc

Add a simplification for slice(crop).

Add a simplification for slice(crop)

---

base/thread_pool.h

This should avoid a few unnecessary task dequeues.

Don't enqueue more than thread_count() workers

---

base/thread_pool.cc
base/thread_pool.h

After the recent thread pool changes, it is now possible to only notify the condition variables waiting on a task if the loop is complete, rather than every time a worker on the loop is done.

Only notify when the task is done

---

base/arithmetic.h
builder/simplify.cc
builder/substitute.cc
builder/test/simplify/simplify.cc
builder/test/substitute.cc
runtime/buffer.h
runtime/test/buffer.cc
runtime/test/evaluate.cc

Add a simplification for slice(constant_buf).

Add a simplification for slice(constant_buf)

---

builder/simplify.cc
builder/test/simplify/simplify.cc

1. Make slice(const_buffer) respect variable substitution.
2. Optimize the Slinky program inside the constant_buffer.

Fix slice(const_buffer) optimization

---

builder/optimizations.cc
builder/test/copy_pipeline.cc

Do not try to propagate strides for contiguous copies.

Do not try to propagate strides for contiguous copies

---

runtime/evaluate.cc
runtime/test/evaluate.cc

Before this PR, we hit an assert in this case.

Fix partially out of bounds `slice_buffer` 
